# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from dotenv import load_dotenv
import os
import logging

# Load .env variables
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '.env'))

log_level = os.getenv('LOG_LEVEL', 'INFO').upper()
logging.basicConfig(level=log_level)
logger = logging.getLogger("bunq-mcp")

from fastapi import FastAPI
from openapi_server.apis.user_api import router as UserApiRouter

app = FastAPI(
    title="Bunq MCP Proxy Minimal",
    description="Minimal FastAPI app for testing the /user endpoint only.",
    version="0.1",
)

app.include_router(UserApiRouter)
