# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminCommentUserListing(BaseModel):
    """
    AdminCommentUserListing
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the comment.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp when the comment was done.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp when the comment was last updated.")
    metadata_uuid: Optional[StrictStr] = Field(default=None, description="The uuid of the metadata.")
    user_id: Optional[StrictInt] = Field(default=None, description="The id of the user this comments relates to.")
    creator_user_id: Optional[StrictInt] = Field(default=None, description="The id of the admin user who added the comment.")
    creator_user_name: Optional[StrictStr] = Field(default=None, description="The name of the admin user who added the comment.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the comment, can be ACTIVE or ARCHIVED. If archived, the support level 3 group is alerted.")
    visibility: Optional[StrictStr] = Field(default=None, description="The visibility of the comment. Can be EVERYONE or COMPLIANCE")
    text: Optional[StrictStr] = Field(default=None, description="The textual content of the comment.")
    attachment: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "metadata_uuid", "user_id", "creator_user_id", "creator_user_name", "status", "visibility", "text", "attachment"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminCommentUserListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "metadata_uuid",
                "user_id",
                "creator_user_id",
                "creator_user_name",
                "status",
                "visibility",
                "text",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachment
        if self.attachment:
            _dict['attachment'] = self.attachment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminCommentUserListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "metadata_uuid": obj.get("metadata_uuid"),
            "user_id": obj.get("user_id"),
            "creator_user_id": obj.get("creator_user_id"),
            "creator_user_name": obj.get("creator_user_name"),
            "status": obj.get("status"),
            "visibility": obj.get("visibility"),
            "text": obj.get("text"),
            "attachment": Attachment.from_dict(obj.get("attachment")) if obj.get("attachment") is not None else None
        })
        return _obj


