# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminTicketEmail(BaseModel):
    """
    AdminTicketEmail
    """ # noqa: E501
    assigned_employee_id: StrictInt = Field(description="The id of the employee to assign to this ticket.")
    email: StrictStr = Field(description="The email we want to send the message to.")
    name: StrictStr = Field(description="The name of the person we want to send the message to.")
    subject: StrictStr = Field(description="The subject of the email")
    employee_skill_required: StrictStr = Field(description="The skill required for the employee to handle this ticket.")
    __properties: ClassVar[List[str]] = ["assigned_employee_id", "email", "name", "subject", "employee_skill_required"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminTicketEmail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminTicketEmail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "assigned_employee_id": obj.get("assigned_employee_id"),
            "email": obj.get("email"),
            "name": obj.get("name"),
            "subject": obj.get("subject"),
            "employee_skill_required": obj.get("employee_skill_required")
        })
        return _obj


