# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminIncidentListing(BaseModel):
    """
    AdminIncidentListing
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status of the incident.")
    type: Optional[StrictStr] = Field(default=None, description="The type of incident.")
    all_display_location: Optional[List[StrictStr]] = Field(default=None, description="The locations where this incident should be displayed.")
    title_ongoing: Optional[StrictStr] = Field(default=None, description="The title of the incident.")
    description_ongoing: Optional[StrictStr] = Field(default=None, description="The user facing message detailing the ongoing incident.")
    title_resolved: Optional[StrictStr] = Field(default=None, description="The title of the incident.")
    description_resolved: Optional[StrictStr] = Field(default=None, description="The user facing message detailing the resolution of the incident.")
    url: Optional[StrictStr] = Field(default=None, description="The link users can navigate to for more details (can be a Together link, or another link if Together is down).")
    label_user_initiator: Optional[Dict[str, Any]] = None
    number_of_subscribed_users: Optional[StrictInt] = Field(default=None, description="The number of users subscribed to updates about the incident.")
    __properties: ClassVar[List[str]] = ["status", "type", "all_display_location", "title_ongoing", "description_ongoing", "title_resolved", "description_resolved", "url", "label_user_initiator", "number_of_subscribed_users"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminIncidentListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "type",
                "all_display_location",
                "title_ongoing",
                "description_ongoing",
                "title_resolved",
                "description_resolved",
                "url",
                "number_of_subscribed_users",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of label_user_initiator
        if self.label_user_initiator:
            _dict['label_user_initiator'] = self.label_user_initiator.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminIncidentListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "type": obj.get("type"),
            "all_display_location": obj.get("all_display_location"),
            "title_ongoing": obj.get("title_ongoing"),
            "description_ongoing": obj.get("description_ongoing"),
            "title_resolved": obj.get("title_resolved"),
            "description_resolved": obj.get("description_resolved"),
            "url": obj.get("url"),
            "label_user_initiator": LabelUser.from_dict(obj.get("label_user_initiator")) if obj.get("label_user_initiator") is not None else None,
            "number_of_subscribed_users": obj.get("number_of_subscribed_users")
        })
        return _obj


