# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminUserDeny(BaseModel):
    """
    AdminUserDeny
    """ # noqa: E501
    iban: Optional[StrictStr] = Field(default=None, description="The IBAN any funds should be refunded to.")
    user_status: StrictStr = Field(description="The status of the user.")
    user_sub_status: StrictStr = Field(description="The sub status of the user.")
    deny_status: StrictStr = Field(description="The status of the user deny.")
    reason: StrictStr = Field(description="The reason for the user deny.")
    comment: Optional[StrictStr] = Field(default=None, description="The comment explain the user deny.")
    refund_method: Optional[StrictStr] = Field(default=None, description="Send \"NO_REFUND\" to not refund the user (only for user status FROZEN). Omitting field or value null means the backend will determine the refund method.")
    __properties: ClassVar[List[str]] = ["iban", "user_status", "user_sub_status", "deny_status", "reason", "comment", "refund_method"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminUserDeny from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminUserDeny from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "iban": obj.get("iban"),
            "user_status": obj.get("user_status"),
            "user_sub_status": obj.get("user_sub_status"),
            "deny_status": obj.get("deny_status"),
            "reason": obj.get("reason"),
            "comment": obj.get("comment"),
            "refund_method": obj.get("refund_method")
        })
        return _obj


