# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.attachment import Attachment
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminPaymentInvestigationListing(BaseModel):
    """
    AdminPaymentInvestigationListing
    """ # noqa: E501
    monetary_account_id: Optional[StrictInt] = Field(default=None, description="The monetary account to which the payment is expected to transfer to.")
    payment_reference: Optional[StrictStr] = Field(default=None, description="The payment reference provided by the user.")
    amount: Optional[Dict[str, Any]] = None
    date_payment_sent: Optional[StrictStr] = Field(default=None, description="The date on which the payment was expected to arrive.")
    account_number_counterparty: Optional[StrictStr] = Field(default=None, description="The account number of the sending party.")
    description: Optional[StrictStr] = Field(default=None, description="The description by the user initiating the payment investigation.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the payment investigation. Can be PENDING, CLOSED, or CANCELLED.")
    investigator: Optional[Dict[str, Any]] = None
    type: Optional[StrictStr] = Field(default=None, description="The type of payment expected, if known. For example: UNKNOWN, SEPA, SWIFT.")
    attachment: Optional[List[Attachment]] = Field(default=None, description="The user attachments attached to the payment investigation.")
    message_result: Optional[StrictStr] = Field(default=None, description="The message by the investigator explaining the result of the payment investigation.")
    __properties: ClassVar[List[str]] = ["monetary_account_id", "payment_reference", "amount", "date_payment_sent", "account_number_counterparty", "description", "status", "investigator", "type", "attachment", "message_result"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminPaymentInvestigationListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "monetary_account_id",
                "payment_reference",
                "date_payment_sent",
                "account_number_counterparty",
                "description",
                "status",
                "type",
                "attachment",
                "message_result",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of investigator
        if self.investigator:
            _dict['investigator'] = self.investigator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attachment (list)
        _items = []
        if self.attachment:
            for _item in self.attachment:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attachment'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminPaymentInvestigationListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "monetary_account_id": obj.get("monetary_account_id"),
            "payment_reference": obj.get("payment_reference"),
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "date_payment_sent": obj.get("date_payment_sent"),
            "account_number_counterparty": obj.get("account_number_counterparty"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "investigator": LabelUser.from_dict(obj.get("investigator")) if obj.get("investigator") is not None else None,
            "type": obj.get("type"),
            "attachment": [Attachment.from_dict(_item) for _item in obj.get("attachment")] if obj.get("attachment") is not None else None,
            "message_result": obj.get("message_result")
        })
        return _obj


