# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminPermissionGroupRead(BaseModel):
    """
    AdminPermissionGroupRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the admin permission group.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the admin permission group's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the admin permission group's last update.")
    created_by: Optional[Dict[str, Any]] = None
    updated_by: Optional[Dict[str, Any]] = None
    group: Optional[Dict[str, Any]] = None
    object_name: Optional[StrictStr] = Field(default=None, description="A string that will match the api object returned by the api.")
    action: Optional[StrictStr] = Field(default=None, description="The action that is allowed when the objectName matches the endpoint.")
    api: Optional[StrictStr] = Field(default=None, description="The api type.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the permission.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "created_by", "updated_by", "group", "object_name", "action", "api", "status"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminPermissionGroupRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "object_name",
                "action",
                "api",
                "status",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updated_by'] = self.updated_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminPermissionGroupRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "created_by": LabelUser.from_dict(obj.get("created_by")) if obj.get("created_by") is not None else None,
            "updated_by": LabelUser.from_dict(obj.get("updated_by")) if obj.get("updated_by") is not None else None,
            "group": AdminGroup.from_dict(obj.get("group")) if obj.get("group") is not None else None,
            "object_name": obj.get("object_name"),
            "action": obj.get("action"),
            "api": obj.get("api"),
            "status": obj.get("status")
        })
        return _obj


