# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminBranchSwitchRead(BaseModel):
    """
    AdminBranchSwitchRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the branch switch")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the branch switch creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the branch switch last update.")
    country_branch_destination: Optional[StrictStr] = Field(default=None, description="The country of the destination branch.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the branch switch.")
    sub_status: Optional[StrictStr] = Field(default=None, description="The sub status of the branch switch.")
    reason: Optional[StrictStr] = Field(default=None, description="The reason of the branch switch.")
    verification_type: Optional[StrictStr] = Field(default=None, description="The verification type required for the branch switch.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "country_branch_destination", "status", "sub_status", "reason", "verification_type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminBranchSwitchRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "country_branch_destination",
                "status",
                "sub_status",
                "reason",
                "verification_type",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminBranchSwitchRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "country_branch_destination": obj.get("country_branch_destination"),
            "status": obj.get("status"),
            "sub_status": obj.get("sub_status"),
            "reason": obj.get("reason"),
            "verification_type": obj.get("verification_type")
        })
        return _obj


