# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminPointChallengeListing(BaseModel):
    """
    AdminPointChallengeListing
    """ # noqa: E501
    title_pending: Optional[StrictStr] = Field(default=None, description="The title of the pending challenge.")
    title_completed_singular: Optional[StrictStr] = Field(default=None, description="The singular form of title of the completed challenge.")
    title_completed_plural: Optional[StrictStr] = Field(default=None, description="The plural form of title of the completed challenge.")
    description_short: Optional[StrictStr] = Field(default=None, description="The short description of the challenge.")
    description_long: Optional[StrictStr] = Field(default=None, description="The long description of the challenge.")
    notification_body: Optional[StrictStr] = Field(default=None, description="The body of the challenge notification.")
    url_together: Optional[StrictStr] = Field(default=None, description="The url to guide user to together page about the challenge.")
    deeplink: Optional[StrictStr] = Field(default=None, description="The deeplink to guide user to complete the challenge.")
    number_of_point: Optional[StrictInt] = Field(default=None, description="The number of points the challenge is worth.")
    category: Optional[StrictStr] = Field(default=None, description="The category of the challenge.")
    recurrence_type: Optional[StrictStr] = Field(default=None, description="The type of the challenge.")
    visibility: Optional[StrictStr] = Field(default=None, description="The visibility of the challenge.")
    user_type_availability: Optional[StrictStr] = Field(default=None, description="The type of user this challenge is available for.")
    order: Optional[StrictInt] = Field(default=None, description="The order of the challenges shown to the user.")
    avatar: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["title_pending", "title_completed_singular", "title_completed_plural", "description_short", "description_long", "notification_body", "url_together", "deeplink", "number_of_point", "category", "recurrence_type", "visibility", "user_type_availability", "order", "avatar"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminPointChallengeListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "title_pending",
                "title_completed_singular",
                "title_completed_plural",
                "description_short",
                "description_long",
                "notification_body",
                "url_together",
                "deeplink",
                "number_of_point",
                "category",
                "recurrence_type",
                "visibility",
                "user_type_availability",
                "order",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of avatar
        if self.avatar:
            _dict['avatar'] = self.avatar.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminPointChallengeListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title_pending": obj.get("title_pending"),
            "title_completed_singular": obj.get("title_completed_singular"),
            "title_completed_plural": obj.get("title_completed_plural"),
            "description_short": obj.get("description_short"),
            "description_long": obj.get("description_long"),
            "notification_body": obj.get("notification_body"),
            "url_together": obj.get("url_together"),
            "deeplink": obj.get("deeplink"),
            "number_of_point": obj.get("number_of_point"),
            "category": obj.get("category"),
            "recurrence_type": obj.get("recurrence_type"),
            "visibility": obj.get("visibility"),
            "user_type_availability": obj.get("user_type_availability"),
            "order": obj.get("order"),
            "avatar": Avatar.from_dict(obj.get("avatar")) if obj.get("avatar") is not None else None
        })
        return _obj


