# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminDeviceListing(BaseModel):
    """
    AdminDeviceListing
    """ # noqa: E501
    device_phone: Optional[Dict[str, Any]] = Field(default=None, alias="DevicePhone")
    device_server: Optional[Dict[str, Any]] = Field(default=None, alias="DeviceServer")
    device_browser: Optional[Dict[str, Any]] = Field(default=None, alias="DeviceBrowser")
    device_watch: Optional[Dict[str, Any]] = Field(default=None, alias="DeviceWatch")
    __properties: ClassVar[List[str]] = ["DevicePhone", "DeviceServer", "DeviceBrowser", "DeviceWatch"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminDeviceListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of device_phone
        if self.device_phone:
            _dict['DevicePhone'] = self.device_phone.to_dict()
        # override the default output from pydantic by calling `to_dict()` of device_server
        if self.device_server:
            _dict['DeviceServer'] = self.device_server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of device_browser
        if self.device_browser:
            _dict['DeviceBrowser'] = self.device_browser.to_dict()
        # override the default output from pydantic by calling `to_dict()` of device_watch
        if self.device_watch:
            _dict['DeviceWatch'] = self.device_watch.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminDeviceListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "DevicePhone": DevicePhone.from_dict(obj.get("DevicePhone")) if obj.get("DevicePhone") is not None else None,
            "DeviceServer": DeviceServer.from_dict(obj.get("DeviceServer")) if obj.get("DeviceServer") is not None else None,
            "DeviceBrowser": DeviceBrowser.from_dict(obj.get("DeviceBrowser")) if obj.get("DeviceBrowser") is not None else None,
            "DeviceWatch": DeviceWatch.from_dict(obj.get("DeviceWatch")) if obj.get("DeviceWatch") is not None else None
        })
        return _obj


