# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdyenCardTransaction(BaseModel):
    """
    AdyenCardTransaction
    """ # noqa: E501
    amount: Optional[Dict[str, Any]] = None
    terminal_id: StrictStr = Field(description="The ID of the Mobile Terminal/Point of Sale on which the card transaction should be started.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the transaction.")
    reference_customer: Optional[StrictStr] = Field(default=None, description="The reference for the card transaction shown to (Eva’s) customer.")
    monetary_account_id: Optional[StrictInt] = Field(default=None, description="The ID of the monetary account the card transaction was started from.")
    adyen_store_id: Optional[StrictInt] = Field(default=None, description="The ID of the Adyen store the card transaction belongs to.")
    label_user: Optional[Dict[str, Any]] = None
    label_user_creator: Optional[Dict[str, Any]] = None
    label_monetary_account: Optional[Dict[str, Any]] = None
    card_brand: Optional[StrictStr] = Field(default=None, description="The customer’s card’s brand.")
    card_pan_masked: Optional[StrictStr] = Field(default=None, description="The customer’s card’s PAN, masked.")
    status_description: Optional[StrictStr] = Field(default=None, description="A message explaining the current state of the transaction.")
    status_description_translated: Optional[StrictStr] = Field(default=None, description="A message to display to the user explaining the current state of the transaction.")
    status_together_url: Optional[StrictStr] = Field(default=None, description="A URL to the together topic explaining the current state of the transaction.")
    receipt_attachment: Optional[Dict[str, Any]] = None
    request_payment_create: Optional[StrictStr] = Field(default=None, description="A JSON string containing the details of the payment request that should be passed to the Adyen Mobile POS SDK.")
    __properties: ClassVar[List[str]] = ["amount", "terminal_id", "status", "reference_customer", "monetary_account_id", "adyen_store_id", "label_user", "label_user_creator", "label_monetary_account", "card_brand", "card_pan_masked", "status_description", "status_description_translated", "status_together_url", "receipt_attachment", "request_payment_create"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdyenCardTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "reference_customer",
                "monetary_account_id",
                "adyen_store_id",
                "card_brand",
                "card_pan_masked",
                "status_description",
                "status_description_translated",
                "status_together_url",
                "request_payment_create",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_user
        if self.label_user:
            _dict['label_user'] = self.label_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_user_creator
        if self.label_user_creator:
            _dict['label_user_creator'] = self.label_user_creator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_monetary_account
        if self.label_monetary_account:
            _dict['label_monetary_account'] = self.label_monetary_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of receipt_attachment
        if self.receipt_attachment:
            _dict['receipt_attachment'] = self.receipt_attachment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdyenCardTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "terminal_id": obj.get("terminal_id"),
            "status": obj.get("status"),
            "reference_customer": obj.get("reference_customer"),
            "monetary_account_id": obj.get("monetary_account_id"),
            "adyen_store_id": obj.get("adyen_store_id"),
            "label_user": LabelUser.from_dict(obj.get("label_user")) if obj.get("label_user") is not None else None,
            "label_user_creator": LabelUser.from_dict(obj.get("label_user_creator")) if obj.get("label_user_creator") is not None else None,
            "label_monetary_account": LabelMonetaryAccount.from_dict(obj.get("label_monetary_account")) if obj.get("label_monetary_account") is not None else None,
            "card_brand": obj.get("card_brand"),
            "card_pan_masked": obj.get("card_pan_masked"),
            "status_description": obj.get("status_description"),
            "status_description_translated": obj.get("status_description_translated"),
            "status_together_url": obj.get("status_together_url"),
            "receipt_attachment": AttachmentMonetaryAccountPayment.from_dict(obj.get("receipt_attachment")) if obj.get("receipt_attachment") is not None else None,
            "request_payment_create": obj.get("request_payment_create")
        })
        return _obj


