# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AllocationItem(BaseModel):
    """
    AllocationItem
    """ # noqa: E501
    membership_uuid: Optional[StrictStr] = Field(default=None, description="The UUID of the RegistryMembership we are allocating money for. Can be provided instead of the \"alias\" field.")
    membership_tricount_id: Optional[StrictInt] = Field(default=None, description="The Tricount ID of the membership for backwards compatibility, to be able to handle changed made offline before the Tricount migration, but synced to the backend after the Tricount migration.")
    alias: Optional[Dict[str, Any]] = None
    type: Optional[StrictStr] = Field(default=None, description="The type of the AllocationItem.")
    amount: Optional[Dict[str, Any]] = None
    amount_local: Optional[Dict[str, Any]] = None
    share_ratio: Optional[StrictInt] = Field(default=None, description="The share ratio of the AllocationItem.")
    membership: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["membership_uuid", "membership_tricount_id", "alias", "type", "amount", "amount_local", "share_ratio", "membership"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AllocationItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_local
        if self.amount_local:
            _dict['amount_local'] = self.amount_local.to_dict()
        # override the default output from pydantic by calling `to_dict()` of membership
        if self.membership:
            _dict['membership'] = self.membership.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AllocationItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "membership_uuid": obj.get("membership_uuid"),
            "membership_tricount_id": obj.get("membership_tricount_id"),
            "alias": Pointer.from_dict(obj.get("alias")) if obj.get("alias") is not None else None,
            "type": obj.get("type"),
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "amount_local": Amount.from_dict(obj.get("amount_local")) if obj.get("amount_local") is not None else None,
            "share_ratio": obj.get("share_ratio"),
            "membership": RegistryMembership.from_dict(obj.get("membership")) if obj.get("membership") is not None else None
        })
        return _obj


