# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AssistantFunctionCallbackEscalationListing(BaseModel):
    """
    AssistantFunctionCallbackEscalationListing
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status of the assistant answer.")
    answer_stream_identifier: Optional[StrictStr] = Field(default=None, description="The stream identifier of the suggested answer to the question.")
    conversation_assistant: Optional[Dict[str, Any]] = None
    conversation_escalation: Optional[Dict[str, Any]] = None
    label_user_admin: Optional[Dict[str, Any]] = None
    expertise: Optional[StrictStr] = Field(default=None, description="The expertise of the callback escalation.")
    priority: Optional[StrictStr] = Field(default=None, description="The priority of the callback escalation.")
    reason: Optional[StrictStr] = Field(default=None, description="The reason of why this callback escalation is created.")
    __properties: ClassVar[List[str]] = ["status", "answer_stream_identifier", "conversation_assistant", "conversation_escalation", "label_user_admin", "expertise", "priority", "reason"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AssistantFunctionCallbackEscalationListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "answer_stream_identifier",
                "expertise",
                "priority",
                "reason",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conversation_assistant
        if self.conversation_assistant:
            _dict['conversation_assistant'] = self.conversation_assistant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conversation_escalation
        if self.conversation_escalation:
            _dict['conversation_escalation'] = self.conversation_escalation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_user_admin
        if self.label_user_admin:
            _dict['label_user_admin'] = self.label_user_admin.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AssistantFunctionCallbackEscalationListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "answer_stream_identifier": obj.get("answer_stream_identifier"),
            "conversation_assistant": AssistantConversation.from_dict(obj.get("conversation_assistant")) if obj.get("conversation_assistant") is not None else None,
            "conversation_escalation": AssistantConversation.from_dict(obj.get("conversation_escalation")) if obj.get("conversation_escalation") is not None else None,
            "label_user_admin": LabelUser.from_dict(obj.get("label_user_admin")) if obj.get("label_user_admin") is not None else None,
            "expertise": obj.get("expertise"),
            "priority": obj.get("priority"),
            "reason": obj.get("reason")
        })
        return _obj


