# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AssistantConversationMessageListing(BaseModel):
    """
    AssistantConversationMessageListing
    """ # noqa: E501
    assistant_message_question: Optional[Dict[str, Any]] = Field(default=None, alias="AssistantMessageQuestion")
    assistant_message_answer: Optional[Dict[str, Any]] = Field(default=None, alias="AssistantMessageAnswer")
    __properties: ClassVar[List[str]] = ["AssistantMessageQuestion", "AssistantMessageAnswer"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AssistantConversationMessageListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of assistant_message_question
        if self.assistant_message_question:
            _dict['AssistantMessageQuestion'] = self.assistant_message_question.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assistant_message_answer
        if self.assistant_message_answer:
            _dict['AssistantMessageAnswer'] = self.assistant_message_answer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AssistantConversationMessageListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AssistantMessageQuestion": AssistantMessageQuestion.from_dict(obj.get("AssistantMessageQuestion")) if obj.get("AssistantMessageQuestion") is not None else None,
            "AssistantMessageAnswer": AssistantMessageAnswer.from_dict(obj.get("AssistantMessageAnswer")) if obj.get("AssistantMessageAnswer") is not None else None
        })
        return _obj


