# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BancontactMerchantTransactionRead(BaseModel):
    """
    BancontactMerchantTransactionRead
    """ # noqa: E501
    monetary_account_id: Optional[StrictInt] = Field(default=None, description="The id of the monetary account this bancontact merchant transaction links to.")
    alias: Optional[Dict[str, Any]] = None
    counterparty_alias: Optional[Dict[str, Any]] = None
    amount_requested: Optional[Dict[str, Any]] = None
    expiration: Optional[StrictStr] = Field(default=None, description="When the transaction will expire.")
    url_redirect: Optional[StrictStr] = Field(default=None, description="The URL to visit complete the bancontact transaction.")
    url_deep_link: Optional[StrictStr] = Field(default=None, description="The deep link to visit complete the bancontact transaction.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the transaction.")
    status_timestamp: Optional[StrictStr] = Field(default=None, description="When the status was last updated.")
    transaction_id: Optional[StrictStr] = Field(default=None, description="The transaction ID of the bancontact transaction.")
    customer_iban: Optional[StrictStr] = Field(default=None, description="The Iban of the customer.")
    description_content: Optional[StrictStr] = Field(default=None, description="The description of the transaction.")
    mutation_id: Optional[StrictInt] = Field(default=None, description="The mutation id of the payout if the transaction has been settled.")
    __properties: ClassVar[List[str]] = ["monetary_account_id", "alias", "counterparty_alias", "amount_requested", "expiration", "url_redirect", "url_deep_link", "status", "status_timestamp", "transaction_id", "customer_iban", "description_content", "mutation_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BancontactMerchantTransactionRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "monetary_account_id",
                "expiration",
                "url_redirect",
                "url_deep_link",
                "status",
                "status_timestamp",
                "transaction_id",
                "customer_iban",
                "description_content",
                "mutation_id",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counterparty_alias
        if self.counterparty_alias:
            _dict['counterparty_alias'] = self.counterparty_alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_requested
        if self.amount_requested:
            _dict['amount_requested'] = self.amount_requested.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BancontactMerchantTransactionRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "monetary_account_id": obj.get("monetary_account_id"),
            "alias": LabelMonetaryAccount.from_dict(obj.get("alias")) if obj.get("alias") is not None else None,
            "counterparty_alias": LabelMonetaryAccount.from_dict(obj.get("counterparty_alias")) if obj.get("counterparty_alias") is not None else None,
            "amount_requested": Amount.from_dict(obj.get("amount_requested")) if obj.get("amount_requested") is not None else None,
            "expiration": obj.get("expiration"),
            "url_redirect": obj.get("url_redirect"),
            "url_deep_link": obj.get("url_deep_link"),
            "status": obj.get("status"),
            "status_timestamp": obj.get("status_timestamp"),
            "transaction_id": obj.get("transaction_id"),
            "customer_iban": obj.get("customer_iban"),
            "description_content": obj.get("description_content"),
            "mutation_id": obj.get("mutation_id")
        })
        return _obj


