# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Benefit(BaseModel):
    """
    Benefit
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="The type of benefit.")
    contact_detail: Optional[Dict[str, Any]] = None
    time_coverage_start: Optional[StrictStr] = Field(default=None, description="The date from which the benefit is valid.")
    time_coverage_end: Optional[StrictStr] = Field(default=None, description="The date till which the benefit is valid.")
    __properties: ClassVar[List[str]] = ["type", "contact_detail", "time_coverage_start", "time_coverage_end"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Benefit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "type",
                "time_coverage_start",
                "time_coverage_end",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of contact_detail
        if self.contact_detail:
            _dict['contact_detail'] = self.contact_detail.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Benefit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "contact_detail": ContactDetail.from_dict(obj.get("contact_detail")) if obj.get("contact_detail") is not None else None,
            "time_coverage_start": obj.get("time_coverage_start"),
            "time_coverage_end": obj.get("time_coverage_end")
        })
        return _obj


