# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BirdeeInvestmentPortfolioBalance(BaseModel):
    """
    BirdeeInvestmentPortfolioBalance
    """ # noqa: E501
    amount_available: Optional[Dict[str, Any]] = None
    amount_deposit_total: Optional[Dict[str, Any]] = None
    amount_withdrawal_total: Optional[Dict[str, Any]] = None
    amount_fee_total: Optional[Dict[str, Any]] = None
    amount_profit: Optional[Dict[str, Any]] = None
    amount_deposit_pending: Optional[Dict[str, Any]] = None
    amount_withdrawal_pending: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["amount_available", "amount_deposit_total", "amount_withdrawal_total", "amount_fee_total", "amount_profit", "amount_deposit_pending", "amount_withdrawal_pending"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BirdeeInvestmentPortfolioBalance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_available
        if self.amount_available:
            _dict['amount_available'] = self.amount_available.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_deposit_total
        if self.amount_deposit_total:
            _dict['amount_deposit_total'] = self.amount_deposit_total.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_withdrawal_total
        if self.amount_withdrawal_total:
            _dict['amount_withdrawal_total'] = self.amount_withdrawal_total.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_fee_total
        if self.amount_fee_total:
            _dict['amount_fee_total'] = self.amount_fee_total.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_profit
        if self.amount_profit:
            _dict['amount_profit'] = self.amount_profit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_deposit_pending
        if self.amount_deposit_pending:
            _dict['amount_deposit_pending'] = self.amount_deposit_pending.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_withdrawal_pending
        if self.amount_withdrawal_pending:
            _dict['amount_withdrawal_pending'] = self.amount_withdrawal_pending.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BirdeeInvestmentPortfolioBalance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount_available": Amount.from_dict(obj.get("amount_available")) if obj.get("amount_available") is not None else None,
            "amount_deposit_total": Amount.from_dict(obj.get("amount_deposit_total")) if obj.get("amount_deposit_total") is not None else None,
            "amount_withdrawal_total": Amount.from_dict(obj.get("amount_withdrawal_total")) if obj.get("amount_withdrawal_total") is not None else None,
            "amount_fee_total": Amount.from_dict(obj.get("amount_fee_total")) if obj.get("amount_fee_total") is not None else None,
            "amount_profit": Amount.from_dict(obj.get("amount_profit")) if obj.get("amount_profit") is not None else None,
            "amount_deposit_pending": Amount.from_dict(obj.get("amount_deposit_pending")) if obj.get("amount_deposit_pending") is not None else None,
            "amount_withdrawal_pending": Amount.from_dict(obj.get("amount_withdrawal_pending")) if obj.get("amount_withdrawal_pending") is not None else None
        })
        return _obj


