# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.birdee_portfolio_allocation import BirdeePortfolioAllocation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BirdeeInvestmentPortfolioRead(BaseModel):
    """
    BirdeeInvestmentPortfolioRead
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="Status of the portfolio.")
    risk_profile_type: Optional[StrictStr] = Field(default=None, description="The type of risk profile associated with the portfolio.")
    investment_theme: Optional[StrictStr] = Field(default=None, description="The investment theme.")
    number_of_strategy_change_annual_maximum: Optional[StrictInt] = Field(default=None, description="Maximum number of strategy changes in a year.")
    number_of_strategy_change_annual_used: Optional[StrictInt] = Field(default=None, description="Maximum number of strategy changes used.")
    name: Optional[StrictStr] = Field(default=None, description="The name associated with the investment portfolio.")
    external_identifier: Optional[StrictStr] = Field(default=None, description="The external identifier of the portfolio.")
    goal: Optional[Dict[str, Any]] = None
    balance: Optional[Dict[str, Any]] = None
    allocations: Optional[List[BirdeePortfolioAllocation]] = Field(default=None, description="The allocations of the investment portfolio.")
    __properties: ClassVar[List[str]] = ["status", "risk_profile_type", "investment_theme", "number_of_strategy_change_annual_maximum", "number_of_strategy_change_annual_used", "name", "external_identifier", "goal", "balance", "allocations"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BirdeeInvestmentPortfolioRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "risk_profile_type",
                "investment_theme",
                "number_of_strategy_change_annual_maximum",
                "number_of_strategy_change_annual_used",
                "name",
                "external_identifier",
                "allocations",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of goal
        if self.goal:
            _dict['goal'] = self.goal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of balance
        if self.balance:
            _dict['balance'] = self.balance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in allocations (list)
        _items = []
        if self.allocations:
            for _item in self.allocations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['allocations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BirdeeInvestmentPortfolioRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "risk_profile_type": obj.get("risk_profile_type"),
            "investment_theme": obj.get("investment_theme"),
            "number_of_strategy_change_annual_maximum": obj.get("number_of_strategy_change_annual_maximum"),
            "number_of_strategy_change_annual_used": obj.get("number_of_strategy_change_annual_used"),
            "name": obj.get("name"),
            "external_identifier": obj.get("external_identifier"),
            "goal": BirdeeInvestmentPortfolioGoal.from_dict(obj.get("goal")) if obj.get("goal") is not None else None,
            "balance": BirdeeInvestmentPortfolioBalance.from_dict(obj.get("balance")) if obj.get("balance") is not None else None,
            "allocations": [BirdeePortfolioAllocation.from_dict(_item) for _item in obj.get("allocations")] if obj.get("allocations") is not None else None
        })
        return _obj


