# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BirdeeCustomerFinancialSituationRead(BaseModel):
    """
    BirdeeCustomerFinancialSituationRead
    """ # noqa: E501
    amount_income_monthly: Optional[Dict[str, Any]] = None
    amount_patrimony_total: Optional[Dict[str, Any]] = None
    patrimony_distribution: Optional[Dict[str, Any]] = None
    patrimony_origin: Optional[StrictStr] = Field(default=None, description="The origin of the user's patrimony.")
    __properties: ClassVar[List[str]] = ["amount_income_monthly", "amount_patrimony_total", "patrimony_distribution", "patrimony_origin"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BirdeeCustomerFinancialSituationRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "patrimony_origin",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_income_monthly
        if self.amount_income_monthly:
            _dict['amount_income_monthly'] = self.amount_income_monthly.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_patrimony_total
        if self.amount_patrimony_total:
            _dict['amount_patrimony_total'] = self.amount_patrimony_total.to_dict()
        # override the default output from pydantic by calling `to_dict()` of patrimony_distribution
        if self.patrimony_distribution:
            _dict['patrimony_distribution'] = self.patrimony_distribution.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BirdeeCustomerFinancialSituationRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount_income_monthly": RangeMoneyAmount.from_dict(obj.get("amount_income_monthly")) if obj.get("amount_income_monthly") is not None else None,
            "amount_patrimony_total": RangeMoneyAmount.from_dict(obj.get("amount_patrimony_total")) if obj.get("amount_patrimony_total") is not None else None,
            "patrimony_distribution": BirdeePatrimonyDistribution.from_dict(obj.get("patrimony_distribution")) if obj.get("patrimony_distribution") is not None else None,
            "patrimony_origin": obj.get("patrimony_origin")
        })
        return _obj


