# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BunqMeTabSettlementListing(BaseModel):
    """
    BunqMeTabSettlementListing
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the BunqMeTabSettlement.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp when the BunqMeTabSettlement was created.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp when the BunqMeTabSettlement was last updated.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the BunqMeTabSettlement. Can be READY_FOR_SETTLEMENT, SETTLED, SETTLEMENT_FAILED or REVERSED.")
    amount_requested: Optional[Dict[str, Any]] = None
    amount_paid: Optional[Dict[str, Any]] = None
    amount_fee: Optional[Dict[str, Any]] = None
    monetary_account_id: Optional[StrictInt] = Field(default=None, description="The monetary account external where the bunq.me payments get transferred to.")
    bunqme_tab: Optional[Dict[str, Any]] = None
    mutation_incoming_id: Optional[StrictInt] = Field(default=None, description="Incoming mutation to be transfered to the monetary account of the bunq.me merchant. Can be ADYEN, SOFORT, BANCONTACT or a bunq transaction.")
    mutation_incoming_payout_id: Optional[StrictInt] = Field(default=None, description="Mutation which is payed to the monetary account settlement of the bunq.me tab. Mutation from bunq.me merchant to bunq.me tab settlement.")
    mutation_outgoing_payout_id: Optional[StrictInt] = Field(default=None, description="Outgoing mutation paid to the IBAN of the bunq.me tab external account.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "status", "amount_requested", "amount_paid", "amount_fee", "monetary_account_id", "bunqme_tab", "mutation_incoming_id", "mutation_incoming_payout_id", "mutation_outgoing_payout_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BunqMeTabSettlementListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "status",
                "monetary_account_id",
                "mutation_incoming_id",
                "mutation_incoming_payout_id",
                "mutation_outgoing_payout_id",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_requested
        if self.amount_requested:
            _dict['amount_requested'] = self.amount_requested.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_paid
        if self.amount_paid:
            _dict['amount_paid'] = self.amount_paid.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_fee
        if self.amount_fee:
            _dict['amount_fee'] = self.amount_fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bunqme_tab
        if self.bunqme_tab:
            _dict['bunqme_tab'] = self.bunqme_tab.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BunqMeTabSettlementListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "status": obj.get("status"),
            "amount_requested": Amount.from_dict(obj.get("amount_requested")) if obj.get("amount_requested") is not None else None,
            "amount_paid": Amount.from_dict(obj.get("amount_paid")) if obj.get("amount_paid") is not None else None,
            "amount_fee": Amount.from_dict(obj.get("amount_fee")) if obj.get("amount_fee") is not None else None,
            "monetary_account_id": obj.get("monetary_account_id"),
            "bunqme_tab": BunqMeTab.from_dict(obj.get("bunqme_tab")) if obj.get("bunqme_tab") is not None else None,
            "mutation_incoming_id": obj.get("mutation_incoming_id"),
            "mutation_incoming_payout_id": obj.get("mutation_incoming_payout_id"),
            "mutation_outgoing_payout_id": obj.get("mutation_outgoing_payout_id")
        })
        return _obj


