# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.chamber_of_commerce_activity import ChamberOfCommerceActivity
from openapi_server.models.chamber_of_commerce_branch import ChamberOfCommerceBranch
from openapi_server.models.chamber_of_commerce_involved import ChamberOfCommerceInvolved
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ChamberOfCommerceExcerptRegistrationListing(BaseModel):
    """
    ChamberOfCommerceExcerptRegistrationListing
    """ # noqa: E501
    created: Optional[StrictStr] = Field(default=None, description="Timestamp of chamber of commerce excerpt creation.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the excerpt. FETCHED is the most recent one, older excerpts will be EXPIRED.")
    chamber_of_commerce_number: Optional[StrictStr] = Field(default=None, description="The chamber of commerce number of on the excerpt.")
    legal_form: Optional[StrictStr] = Field(default=None, description="The legal form of the company.")
    legal_form_detailed: Optional[StrictStr] = Field(default=None, description="The detail legal form of the company.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the company.")
    trade_name: Optional[StrictStr] = Field(default=None, description="The trade name of the company.")
    amount_employee: Optional[StrictInt] = Field(default=None, description="The amount of employees in the company.")
    enterprise_visit_address: Optional[Dict[str, Any]] = None
    all_trade_name: Optional[List[StrictStr]] = Field(default=None, description="The trade names of the company if multiple.")
    all_branch: Optional[List[ChamberOfCommerceBranch]] = Field(default=None, description="All the branches associated with the company.")
    all_involved: Optional[List[ChamberOfCommerceInvolved]] = Field(default=None, description="All the entities involved with the company.")
    all_activity: Optional[List[ChamberOfCommerceActivity]] = Field(default=None, description="All the activities of the company.")
    date_registration_start: Optional[StrictStr] = Field(default=None, description="The date the company was registered.")
    date_registration_end: Optional[StrictStr] = Field(default=None, description="The date the company was unregistered.")
    date_deactivation: Optional[StrictStr] = Field(default=None, description="The date the company was deactivated.")
    __properties: ClassVar[List[str]] = ["created", "status", "chamber_of_commerce_number", "legal_form", "legal_form_detailed", "name", "trade_name", "amount_employee", "enterprise_visit_address", "all_trade_name", "all_branch", "all_involved", "all_activity", "date_registration_start", "date_registration_end", "date_deactivation"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChamberOfCommerceExcerptRegistrationListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "created",
                "status",
                "chamber_of_commerce_number",
                "legal_form",
                "legal_form_detailed",
                "name",
                "trade_name",
                "amount_employee",
                "all_trade_name",
                "all_branch",
                "all_involved",
                "all_activity",
                "date_registration_start",
                "date_registration_end",
                "date_deactivation",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of enterprise_visit_address
        if self.enterprise_visit_address:
            _dict['enterprise_visit_address'] = self.enterprise_visit_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in all_branch (list)
        _items = []
        if self.all_branch:
            for _item in self.all_branch:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_branch'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in all_involved (list)
        _items = []
        if self.all_involved:
            for _item in self.all_involved:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_involved'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in all_activity (list)
        _items = []
        if self.all_activity:
            for _item in self.all_activity:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_activity'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ChamberOfCommerceExcerptRegistrationListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "status": obj.get("status"),
            "chamber_of_commerce_number": obj.get("chamber_of_commerce_number"),
            "legal_form": obj.get("legal_form"),
            "legal_form_detailed": obj.get("legal_form_detailed"),
            "name": obj.get("name"),
            "trade_name": obj.get("trade_name"),
            "amount_employee": obj.get("amount_employee"),
            "enterprise_visit_address": Address.from_dict(obj.get("enterprise_visit_address")) if obj.get("enterprise_visit_address") is not None else None,
            "all_trade_name": obj.get("all_trade_name"),
            "all_branch": [ChamberOfCommerceBranch.from_dict(_item) for _item in obj.get("all_branch")] if obj.get("all_branch") is not None else None,
            "all_involved": [ChamberOfCommerceInvolved.from_dict(_item) for _item in obj.get("all_involved")] if obj.get("all_involved") is not None else None,
            "all_activity": [ChamberOfCommerceActivity.from_dict(_item) for _item in obj.get("all_activity")] if obj.get("all_activity") is not None else None,
            "date_registration_start": obj.get("date_registration_start"),
            "date_registration_end": obj.get("date_registration_end"),
            "date_deactivation": obj.get("date_deactivation")
        })
        return _obj


