# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.company_lookup_legal_representative import CompanyLookupLegalRepresentative
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CompanyLookupUserListing(BaseModel):
    """
    CompanyLookupUserListing
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the company lookup.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp when the company lookup was done.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp when the company lookup was last updated.")
    metadata_uuid: Optional[StrictStr] = Field(default=None, description="The uuid of the metadata.")
    type: Optional[StrictStr] = Field(default=None, description="The type of company lookup: PARTIAL or FULL.")
    chamber_of_commerce_number: Optional[StrictStr] = Field(default=None, description="The chamber of commerce number of the company.")
    country: Optional[StrictStr] = Field(default=None, description="The country of the company.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the company.")
    legal_form: Optional[StrictStr] = Field(default=None, description="The comapny's legal form.")
    vat_number: Optional[StrictStr] = Field(default=None, description="The VAT number of the company.")
    incorporation_date: Optional[StrictStr] = Field(default=None, description="The creation date of the company.")
    number_of_employee: Optional[StrictInt] = Field(default=None, description="The number of employees in the company.")
    chamber_of_commerce_status: Optional[StrictStr] = Field(default=None, description="The status of the company according to the lookup.")
    address: Optional[Dict[str, Any]] = None
    all_legal_representative: Optional[List[CompanyLookupLegalRepresentative]] = Field(default=None, description="List of all legal representatives.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "metadata_uuid", "type", "chamber_of_commerce_number", "country", "name", "legal_form", "vat_number", "incorporation_date", "number_of_employee", "chamber_of_commerce_status", "address", "all_legal_representative"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CompanyLookupUserListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "metadata_uuid",
                "type",
                "chamber_of_commerce_number",
                "country",
                "name",
                "legal_form",
                "vat_number",
                "incorporation_date",
                "number_of_employee",
                "chamber_of_commerce_status",
                "all_legal_representative",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in all_legal_representative (list)
        _items = []
        if self.all_legal_representative:
            for _item in self.all_legal_representative:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_legal_representative'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CompanyLookupUserListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "metadata_uuid": obj.get("metadata_uuid"),
            "type": obj.get("type"),
            "chamber_of_commerce_number": obj.get("chamber_of_commerce_number"),
            "country": obj.get("country"),
            "name": obj.get("name"),
            "legal_form": obj.get("legal_form"),
            "vat_number": obj.get("vat_number"),
            "incorporation_date": obj.get("incorporation_date"),
            "number_of_employee": obj.get("number_of_employee"),
            "chamber_of_commerce_status": obj.get("chamber_of_commerce_status"),
            "address": Address.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "all_legal_representative": [CompanyLookupLegalRepresentative.from_dict(_item) for _item in obj.get("all_legal_representative")] if obj.get("all_legal_representative") is not None else None
        })
        return _obj


