# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.credit_line_offer_document import CreditLineOfferDocument
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreditLineOfferRead(BaseModel):
    """
    CreditLineOfferRead
    """ # noqa: E501
    user_id: Optional[StrictInt] = Field(default=None, description="The ID of the user this offer is made out to.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the offer.")
    amount_requested: Optional[Dict[str, Any]] = None
    amount: Optional[Dict[str, Any]] = None
    time_expiry: Optional[StrictStr] = Field(default=None, description="The time when this offer expires.")
    documents: Optional[List[CreditLineOfferDocument]] = Field(default=None, description="Legal documents for the offer.")
    __properties: ClassVar[List[str]] = ["user_id", "status", "amount_requested", "amount", "time_expiry", "documents"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreditLineOfferRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "user_id",
                "status",
                "time_expiry",
                "documents",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_requested
        if self.amount_requested:
            _dict['amount_requested'] = self.amount_requested.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item in self.documents:
                if _item:
                    _items.append(_item.to_dict())
            _dict['documents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreditLineOfferRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "status": obj.get("status"),
            "amount_requested": Amount.from_dict(obj.get("amount_requested")) if obj.get("amount_requested") is not None else None,
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "time_expiry": obj.get("time_expiry"),
            "documents": [CreditLineOfferDocument.from_dict(_item) for _item in obj.get("documents")] if obj.get("documents") is not None else None
        })
        return _obj


