# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DowJonesFilter(BaseModel):
    """
    DowJonesFilter
    """ # noqa: E501
    dow_jones_id: StrictInt = Field(description="The external Dow Jones id.")
    action: StrictStr = Field(description="The action for the filter. Can be ALLOW, DISALLOW or ALLOW_WITH_ASSESSMENT.")
    comment: StrictStr = Field(description="A comment explaining why the dow jones entry was created and/or updated.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the dow jones filter. Can be  ENABLED or DISABLED")
    filter_target: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["dow_jones_id", "action", "comment", "status", "filter_target"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DowJonesFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filter_target
        if self.filter_target:
            _dict['filter_target'] = self.filter_target.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DowJonesFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dow_jones_id": obj.get("dow_jones_id"),
            "action": obj.get("action"),
            "comment": obj.get("comment"),
            "status": obj.get("status"),
            "filter_target": DowJonesFilterTarget.from_dict(obj.get("filter_target")) if obj.get("filter_target") is not None else None
        })
        return _obj


