# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.attachment_monetary_account_payment import AttachmentMonetaryAccountPayment
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DraftPaymentEntry(BaseModel):
    """
    DraftPaymentEntry
    """ # noqa: E501
    amount: Optional[Dict[str, Any]] = None
    counterparty_alias: Optional[Dict[str, Any]] = None
    description: Optional[StrictStr] = Field(default=None, description="The description for the DraftPayment. Maximum 140 characters for DraftPayments to external IBANs, 9000 characters for DraftPayments to only other bunq MonetaryAccounts.")
    merchant_reference: Optional[StrictStr] = Field(default=None, description="Optional data to be included with the Payment specific to the merchant.")
    attachment: Optional[List[AttachmentMonetaryAccountPayment]] = Field(default=None, description="The Attachments attached to the DraftPayment.")
    id: Optional[StrictInt] = Field(default=None, description="The id of the draft payment entry.")
    alias: Optional[Dict[str, Any]] = None
    type: Optional[StrictStr] = Field(default=None, description="The type of the draft payment entry.")
    __properties: ClassVar[List[str]] = ["amount", "counterparty_alias", "description", "merchant_reference", "attachment", "id", "alias", "type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DraftPaymentEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "type",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counterparty_alias
        if self.counterparty_alias:
            _dict['counterparty_alias'] = self.counterparty_alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attachment (list)
        _items = []
        if self.attachment:
            for _item in self.attachment:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attachment'] = _items
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DraftPaymentEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "counterparty_alias": LabelMonetaryAccount.from_dict(obj.get("counterparty_alias")) if obj.get("counterparty_alias") is not None else None,
            "description": obj.get("description"),
            "merchant_reference": obj.get("merchant_reference"),
            "attachment": [AttachmentMonetaryAccountPayment.from_dict(_item) for _item in obj.get("attachment")] if obj.get("attachment") is not None else None,
            "id": obj.get("id"),
            "alias": LabelMonetaryAccount.from_dict(obj.get("alias")) if obj.get("alias") is not None else None,
            "type": obj.get("type")
        })
        return _obj


