# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FeatureAccessListing(BaseModel):
    """
    FeatureAccessListing
    """ # noqa: E501
    public_uuid: Optional[StrictStr] = Field(default=None, description="The public UUID of the feature access.")
    type: Optional[StrictStr] = Field(default=None, description="The type of feature.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the feature.")
    label_user_admin_updated_last: Optional[Dict[str, Any]] = None
    all_restriction: Optional[List[StrictStr]] = Field(default=None, description="The restrictions for the feature.")
    __properties: ClassVar[List[str]] = ["public_uuid", "type", "status", "label_user_admin_updated_last", "all_restriction"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FeatureAccessListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "public_uuid",
                "type",
                "status",
                "all_restriction",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of label_user_admin_updated_last
        if self.label_user_admin_updated_last:
            _dict['label_user_admin_updated_last'] = self.label_user_admin_updated_last.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FeatureAccessListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "public_uuid": obj.get("public_uuid"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "label_user_admin_updated_last": LabelUser.from_dict(obj.get("label_user_admin_updated_last")) if obj.get("label_user_admin_updated_last") is not None else None,
            "all_restriction": obj.get("all_restriction")
        })
        return _obj


