# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FlarumDiscussionRatingPublicGuestListing(BaseModel):
    """
    FlarumDiscussionRatingPublicGuestListing
    """ # noqa: E501
    flarum_discussion_id: Optional[StrictInt] = Field(default=None, description="The ID of the Flarum discussion.")
    rating: Optional[StrictStr] = Field(default=None, description="The rating given to this Flarum discussion.")
    reason: Optional[StrictStr] = Field(default=None, description="The reason provided for the rating.")
    comment: Optional[StrictStr] = Field(default=None, description="An optional comment to accompany the rating.")
    pointer: Optional[Dict[str, Any]] = None
    label_user: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["flarum_discussion_id", "rating", "reason", "comment", "pointer", "label_user"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FlarumDiscussionRatingPublicGuestListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "flarum_discussion_id",
                "rating",
                "reason",
                "comment",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pointer
        if self.pointer:
            _dict['pointer'] = self.pointer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_user
        if self.label_user:
            _dict['label_user'] = self.label_user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FlarumDiscussionRatingPublicGuestListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "flarum_discussion_id": obj.get("flarum_discussion_id"),
            "rating": obj.get("rating"),
            "reason": obj.get("reason"),
            "comment": obj.get("comment"),
            "pointer": Pointer.from_dict(obj.get("pointer")) if obj.get("pointer") is not None else None,
            "label_user": LabelUser.from_dict(obj.get("label_user")) if obj.get("label_user") is not None else None
        })
        return _obj


