# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GovernmentReferralPortalMetadata(BaseModel):
    """
    GovernmentReferralPortalMetadata
    """ # noqa: E501
    legal_basis: Optional[StrictStr] = Field(default=None, description="Possible 'Legal Ground' values are documented in the 'VB Interface Specification' document")
    question_identifier: Optional[StrictStr] = Field(default=None, description="The question identifier consists of 'VB-' and 9 numbers; the question identifier is randomly generated and always unique")
    bank_identifier: Optional[StrictStr] = Field(default=None, description="The bank identifier is based on the international bank identifier of a bank. Possible 'Bank Identifier' values are documented in the 'VB Interface specification' document")
    question_type: StrictStr = Field(description="The question type of this request")
    request_send_time_stamp: StrictStr = Field(description="Timestamp of the VB request; in accordance with ISO standard 8601")
    requester_organisation: Optional[StrictStr] = Field(default=None, description="Organisation of the requester.")
    requester_full_name: Optional[StrictStr] = Field(default=None, description="Initials and the lastname of the requester.")
    requester_email: Optional[StrictStr] = Field(default=None, description="E-mail address of the requester.")
    authorised: Optional[StrictBool] = Field(default=None, description="Whether or not the requester is authorised.")
    vb_user_email: Optional[StrictStr] = Field(default=None, description="E-mail address of the requester.")
    unique_reference_number: Optional[StrictStr] = Field(default=None, description="A unique reference number for the requester.")
    name_authoriser: Optional[StrictStr] = Field(default=None, description="The name of the authoriser of the requester.")
    data_time_stamp: Optional[StrictBool] = Field(default=None, description="A timestamp")
    __properties: ClassVar[List[str]] = ["legal_basis", "question_identifier", "bank_identifier", "question_type", "request_send_time_stamp", "requester_organisation", "requester_full_name", "requester_email", "authorised", "vb_user_email", "unique_reference_number", "name_authoriser", "data_time_stamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GovernmentReferralPortalMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "data_time_stamp",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GovernmentReferralPortalMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "legal_basis": obj.get("legal_basis"),
            "question_identifier": obj.get("question_identifier"),
            "bank_identifier": obj.get("bank_identifier"),
            "question_type": obj.get("question_type"),
            "request_send_time_stamp": obj.get("request_send_time_stamp"),
            "requester_organisation": obj.get("requester_organisation"),
            "requester_full_name": obj.get("requester_full_name"),
            "requester_email": obj.get("requester_email"),
            "authorised": obj.get("authorised"),
            "vb_user_email": obj.get("vb_user_email"),
            "unique_reference_number": obj.get("unique_reference_number"),
            "name_authoriser": obj.get("name_authoriser"),
            "data_time_stamp": obj.get("data_time_stamp")
        })
        return _obj


