# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IdealIssuerKeyObject(BaseModel):
    """
    IdealIssuerKeyObject
    """ # noqa: E501
    kty: Optional[StrictStr] = Field(default=None, description="The type of the key.")
    crv: Optional[StrictStr] = Field(default=None, description="The curve of the key, if the key is an elliptic curve key.")
    x: Optional[StrictStr] = Field(default=None, description="The x-coordinate on the curve, if the key is an elliptic curve key.")
    y: Optional[StrictStr] = Field(default=None, description="The y-coordinate on the curve, if the key is an elliptic curve key.")
    kid: Optional[StrictStr] = Field(default=None, description="The identifier of the key.")
    x5t_s256: Optional[StrictStr] = Field(default=None, description="The sha-256 fingerprint of the key.", alias="x5t#S256")
    x5c: Optional[List[StrictStr]] = Field(default=None, description="The certificate chain of the key.")
    use: Optional[StrictStr] = Field(default=None, description="The use case of the key.")
    alg: Optional[StrictStr] = Field(default=None, description="The algorithm of the key.")
    __properties: ClassVar[List[str]] = ["kty", "crv", "x", "y", "kid", "x5t#S256", "x5c", "use", "alg"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IdealIssuerKeyObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "kty",
                "crv",
                "x",
                "y",
                "kid",
                "x5t_s256",
                "x5c",
                "use",
                "alg",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IdealIssuerKeyObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kty": obj.get("kty"),
            "crv": obj.get("crv"),
            "x": obj.get("x"),
            "y": obj.get("y"),
            "kid": obj.get("kid"),
            "x5t#S256": obj.get("x5t#S256"),
            "x5c": obj.get("x5c"),
            "use": obj.get("use"),
            "alg": obj.get("alg")
        })
        return _obj


