# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.insight_savings_actual import InsightSavingsActual
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InsightSavingsListing(BaseModel):
    """
    InsightSavingsListing
    """ # noqa: E501
    currency: Optional[StrictStr] = Field(default=None, description="The currency for this insights.")
    potential: Optional[Dict[str, Any]] = None
    actual: Optional[List[InsightSavingsActual]] = Field(default=None, description="The actual auto saved amount.")
    __properties: ClassVar[List[str]] = ["currency", "potential", "actual"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InsightSavingsListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "currency",
                "actual",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of potential
        if self.potential:
            _dict['potential'] = self.potential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in actual (list)
        _items = []
        if self.actual:
            for _item in self.actual:
                if _item:
                    _items.append(_item.to_dict())
            _dict['actual'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InsightSavingsListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "potential": Amount.from_dict(obj.get("potential")) if obj.get("potential") is not None else None,
            "actual": [InsightSavingsActual.from_dict(_item) for _item in obj.get("actual")] if obj.get("actual") is not None else None
        })
        return _obj


