# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.user_person_business import UserPersonBusiness
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InsolvencyCaseRead(BaseModel):
    """
    InsolvencyCaseRead
    """ # noqa: E501
    insolvency_case_external_reference: Optional[StrictStr] = Field(default=None, description="The insolvency id that is stored in Rechtspraak's system.")
    insolvency_case_publication_reference: Optional[StrictStr] = Field(default=None, description="The insolvency publication id that is stored in Rechtspraak's system.")
    date_of_publication: Optional[StrictStr] = Field(default=None, description="The date on when this case has been publicated.")
    publication_type: Optional[StrictStr] = Field(default=None, description="The code that determines the type of publications.")
    user_person_date_of_birth: Optional[StrictStr] = Field(default=None, description="The birth date of the person belonging to this case.")
    user_person_place_of_birth: Optional[StrictStr] = Field(default=None, description="The place where the user of this case has been born.")
    user_person_initials: Optional[StrictStr] = Field(default=None, description="The initials of the user that belongs to this case.")
    user_person_full_name: Optional[StrictStr] = Field(default=None, description="The full name of the user that belongs to this case.")
    user_person_country_of_birth: Optional[StrictStr] = Field(default=None, description="The country where the user was born")
    user_person_businesses: Optional[List[UserPersonBusiness]] = Field(default=None, description="All the businesses that belongs to this particular user person")
    user_company_chamber_of_commerce_number: Optional[StrictStr] = Field(default=None, description="The company's chamber of commerce number.")
    __properties: ClassVar[List[str]] = ["insolvency_case_external_reference", "insolvency_case_publication_reference", "date_of_publication", "publication_type", "user_person_date_of_birth", "user_person_place_of_birth", "user_person_initials", "user_person_full_name", "user_person_country_of_birth", "user_person_businesses", "user_company_chamber_of_commerce_number"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InsolvencyCaseRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "insolvency_case_external_reference",
                "insolvency_case_publication_reference",
                "date_of_publication",
                "publication_type",
                "user_person_date_of_birth",
                "user_person_place_of_birth",
                "user_person_initials",
                "user_person_full_name",
                "user_person_country_of_birth",
                "user_person_businesses",
                "user_company_chamber_of_commerce_number",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in user_person_businesses (list)
        _items = []
        if self.user_person_businesses:
            for _item in self.user_person_businesses:
                if _item:
                    _items.append(_item.to_dict())
            _dict['user_person_businesses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InsolvencyCaseRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "insolvency_case_external_reference": obj.get("insolvency_case_external_reference"),
            "insolvency_case_publication_reference": obj.get("insolvency_case_publication_reference"),
            "date_of_publication": obj.get("date_of_publication"),
            "publication_type": obj.get("publication_type"),
            "user_person_date_of_birth": obj.get("user_person_date_of_birth"),
            "user_person_place_of_birth": obj.get("user_person_place_of_birth"),
            "user_person_initials": obj.get("user_person_initials"),
            "user_person_full_name": obj.get("user_person_full_name"),
            "user_person_country_of_birth": obj.get("user_person_country_of_birth"),
            "user_person_businesses": [UserPersonBusiness.from_dict(_item) for _item in obj.get("user_person_businesses")] if obj.get("user_person_businesses") is not None else None,
            "user_company_chamber_of_commerce_number": obj.get("user_company_chamber_of_commerce_number")
        })
        return _obj


