# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InstantPaymentRecallRequestIncoming(BaseModel):
    """
    InstantPaymentRecallRequestIncoming
    """ # noqa: E501
    status: StrictStr = Field(description="The status of the recall request.")
    reject_reason: Optional[StrictStr] = Field(default=None, description="The reason the recall was rejected (if status is REJECTED).")
    additional_information: Optional[StrictStr] = Field(default=None, description="Additional information when the recall was rejected (if status is REJECTED).")
    amount_returned: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["status", "reject_reason", "additional_information", "amount_returned"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InstantPaymentRecallRequestIncoming from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_returned
        if self.amount_returned:
            _dict['amount_returned'] = self.amount_returned.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InstantPaymentRecallRequestIncoming from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "reject_reason": obj.get("reject_reason"),
            "additional_information": obj.get("additional_information"),
            "amount_returned": Amount.from_dict(obj.get("amount_returned")) if obj.get("amount_returned") is not None else None
        })
        return _obj


