# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.kraken_asset import KrakenAsset
from openapi_server.models.kraken_asset_account_portfolio import KrakenAssetAccountPortfolio
from openapi_server.models.kraken_asset_spotlight import KrakenAssetSpotlight
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class KrakenOverviewListing(BaseModel):
    """
    KrakenOverviewListing
    """ # noqa: E501
    account_available: Optional[Dict[str, Any]] = None
    account: Optional[Dict[str, Any]] = None
    all_asset: Optional[List[KrakenAsset]] = Field(default=None, description="Kraken instruments.")
    all_asset_spotlight: Optional[List[KrakenAssetSpotlight]] = Field(default=None, description="All kraken assets with in spotlight.")
    all_asset_account_portfolio: Optional[List[KrakenAssetAccountPortfolio]] = Field(default=None, description="All kraken assets in account portfolio.")
    portfolio_history: Optional[Dict[str, Any]] = None
    portfolio_summary: Optional[Dict[str, Any]] = None
    promotion: Optional[Dict[str, Any]] = None
    all_asset_favorite: Optional[List[StrictStr]] = Field(default=None, description="All favorite assets for user.")
    __properties: ClassVar[List[str]] = ["account_available", "account", "all_asset", "all_asset_spotlight", "all_asset_account_portfolio", "portfolio_history", "portfolio_summary", "promotion", "all_asset_favorite"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KrakenOverviewListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "all_asset",
                "all_asset_spotlight",
                "all_asset_account_portfolio",
                "all_asset_favorite",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account_available
        if self.account_available:
            _dict['account_available'] = self.account_available.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in all_asset (list)
        _items = []
        if self.all_asset:
            for _item in self.all_asset:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_asset'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in all_asset_spotlight (list)
        _items = []
        if self.all_asset_spotlight:
            for _item in self.all_asset_spotlight:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_asset_spotlight'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in all_asset_account_portfolio (list)
        _items = []
        if self.all_asset_account_portfolio:
            for _item in self.all_asset_account_portfolio:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_asset_account_portfolio'] = _items
        # override the default output from pydantic by calling `to_dict()` of portfolio_history
        if self.portfolio_history:
            _dict['portfolio_history'] = self.portfolio_history.to_dict()
        # override the default output from pydantic by calling `to_dict()` of portfolio_summary
        if self.portfolio_summary:
            _dict['portfolio_summary'] = self.portfolio_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of promotion
        if self.promotion:
            _dict['promotion'] = self.promotion.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of KrakenOverviewListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_available": KrakenAccountAvailable.from_dict(obj.get("account_available")) if obj.get("account_available") is not None else None,
            "account": obj.get("account"),
            "all_asset": [KrakenAsset.from_dict(_item) for _item in obj.get("all_asset")] if obj.get("all_asset") is not None else None,
            "all_asset_spotlight": [KrakenAssetSpotlight.from_dict(_item) for _item in obj.get("all_asset_spotlight")] if obj.get("all_asset_spotlight") is not None else None,
            "all_asset_account_portfolio": [KrakenAssetAccountPortfolio.from_dict(_item) for _item in obj.get("all_asset_account_portfolio")] if obj.get("all_asset_account_portfolio") is not None else None,
            "portfolio_history": KrakenPortfolioValuationHistory.from_dict(obj.get("portfolio_history")) if obj.get("portfolio_history") is not None else None,
            "portfolio_summary": KrakenPortfolioSummary.from_dict(obj.get("portfolio_summary")) if obj.get("portfolio_summary") is not None else None,
            "promotion": KrakenPromotion.from_dict(obj.get("promotion")) if obj.get("promotion") is not None else None,
            "all_asset_favorite": obj.get("all_asset_favorite")
        })
        return _obj


