# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class KrakenQuote(BaseModel):
    """
    KrakenQuote
    """ # noqa: E501
    amount: Optional[Dict[str, Any]] = None
    unit_source: Dict[str, Any]
    unit_target: Dict[str, Any]
    side_fixed: StrictStr = Field(description="The fixed side for this quote.")
    status: Optional[StrictStr] = Field(default=None, description="The status to update to.")
    alias: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["amount", "unit_source", "unit_target", "side_fixed", "status", "alias"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KrakenQuote from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of unit_source
        if self.unit_source:
            _dict['unit_source'] = self.unit_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of unit_target
        if self.unit_target:
            _dict['unit_target'] = self.unit_target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of KrakenQuote from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": GenericAmount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "unit_source": AmountUnit.from_dict(obj.get("unit_source")) if obj.get("unit_source") is not None else None,
            "unit_target": AmountUnit.from_dict(obj.get("unit_target")) if obj.get("unit_target") is not None else None,
            "side_fixed": obj.get("side_fixed"),
            "status": obj.get("status"),
            "alias": Pointer.from_dict(obj.get("alias")) if obj.get("alias") is not None else None
        })
        return _obj


