# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class KrakenPromotion(BaseModel):
    """
    KrakenPromotion
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Asset name for this promotion.")
    type: Optional[StrictStr] = Field(default=None, description="Type of this promotion.")
    amount_promotion: Optional[Dict[str, Any]] = None
    amount_order_minimum: Optional[Dict[str, Any]] = None
    title: Optional[StrictStr] = Field(default=None, description="Title for this promotion.")
    transaction_type: Optional[StrictStr] = Field(default=None, description="Eligible transaction type for this promotion.")
    spots_available: Optional[StrictInt] = Field(default=None, description="Spots available for this promotion.")
    title_translated: Optional[StrictStr] = Field(default=None, description="Translated title for this promotion.")
    description: Optional[StrictStr] = Field(default=None, description="Description for this promotion.")
    description_translated: Optional[StrictStr] = Field(default=None, description="Translated description for this promotion.")
    description_quote: Optional[StrictStr] = Field(default=None, description="Description for this promotion to show in quote screen.")
    description_quote_translated: Optional[StrictStr] = Field(default=None, description="Translated description for this promotion to show in quote screen.")
    __properties: ClassVar[List[str]] = ["name", "type", "amount_promotion", "amount_order_minimum", "title", "transaction_type", "spots_available", "title_translated", "description", "description_translated", "description_quote", "description_quote_translated"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KrakenPromotion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "name",
                "type",
                "title",
                "transaction_type",
                "spots_available",
                "title_translated",
                "description",
                "description_translated",
                "description_quote",
                "description_quote_translated",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_promotion
        if self.amount_promotion:
            _dict['amount_promotion'] = self.amount_promotion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_order_minimum
        if self.amount_order_minimum:
            _dict['amount_order_minimum'] = self.amount_order_minimum.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of KrakenPromotion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "amount_promotion": Amount.from_dict(obj.get("amount_promotion")) if obj.get("amount_promotion") is not None else None,
            "amount_order_minimum": Amount.from_dict(obj.get("amount_order_minimum")) if obj.get("amount_order_minimum") is not None else None,
            "title": obj.get("title"),
            "transaction_type": obj.get("transaction_type"),
            "spots_available": obj.get("spots_available"),
            "title_translated": obj.get("title_translated"),
            "description": obj.get("description"),
            "description_translated": obj.get("description_translated"),
            "description_quote": obj.get("description_quote"),
            "description_quote_translated": obj.get("description_quote_translated")
        })
        return _obj


