# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class KrakenTransactionListing(BaseModel):
    """
    KrakenTransactionListing
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status of the transaction.")
    status_description: Optional[StrictStr] = Field(default=None, description="The status of the transaction.")
    status_description_translated: Optional[StrictStr] = Field(default=None, description="The translated status of the transaction.")
    type: Optional[StrictStr] = Field(default=None, description="Type of the order.")
    amount_order_source: Optional[Dict[str, Any]] = None
    amount_billing_source: Optional[Dict[str, Any]] = None
    amount_order_source_local: Optional[Dict[str, Any]] = None
    amount_billing_source_local: Optional[Dict[str, Any]] = None
    amount_order_target: Optional[Dict[str, Any]] = None
    amount_billing_target: Optional[Dict[str, Any]] = None
    amount_order_target_local: Optional[Dict[str, Any]] = None
    amount_billing_target_local: Optional[Dict[str, Any]] = None
    amount_fee: Optional[Dict[str, Any]] = None
    amount_fee_local: Optional[Dict[str, Any]] = None
    amount_unit_price: Optional[Dict[str, Any]] = None
    external_identifier: Optional[StrictStr] = Field(default=None, description="External identifier of this order at Kraken.")
    label_user: Optional[Dict[str, Any]] = None
    label_monetary_account: Optional[Dict[str, Any]] = None
    counter_label_monetary_account: Optional[Dict[str, Any]] = None
    event_id: Optional[StrictInt] = Field(default=None, description="The id of the event of transaction.")
    asset_name_requested: Optional[StrictStr] = Field(default=None, description="The requested asset name, used to display the right side of this transaction.")
    source: Optional[StrictStr] = Field(default=None, description="Source of this kraken transaction.")
    quote_fee: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["status", "status_description", "status_description_translated", "type", "amount_order_source", "amount_billing_source", "amount_order_source_local", "amount_billing_source_local", "amount_order_target", "amount_billing_target", "amount_order_target_local", "amount_billing_target_local", "amount_fee", "amount_fee_local", "amount_unit_price", "external_identifier", "label_user", "label_monetary_account", "counter_label_monetary_account", "event_id", "asset_name_requested", "source", "quote_fee"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KrakenTransactionListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "status_description",
                "status_description_translated",
                "type",
                "external_identifier",
                "event_id",
                "asset_name_requested",
                "source",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_order_source
        if self.amount_order_source:
            _dict['amount_order_source'] = self.amount_order_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_billing_source
        if self.amount_billing_source:
            _dict['amount_billing_source'] = self.amount_billing_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_order_source_local
        if self.amount_order_source_local:
            _dict['amount_order_source_local'] = self.amount_order_source_local.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_billing_source_local
        if self.amount_billing_source_local:
            _dict['amount_billing_source_local'] = self.amount_billing_source_local.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_order_target
        if self.amount_order_target:
            _dict['amount_order_target'] = self.amount_order_target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_billing_target
        if self.amount_billing_target:
            _dict['amount_billing_target'] = self.amount_billing_target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_order_target_local
        if self.amount_order_target_local:
            _dict['amount_order_target_local'] = self.amount_order_target_local.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_billing_target_local
        if self.amount_billing_target_local:
            _dict['amount_billing_target_local'] = self.amount_billing_target_local.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_fee
        if self.amount_fee:
            _dict['amount_fee'] = self.amount_fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_fee_local
        if self.amount_fee_local:
            _dict['amount_fee_local'] = self.amount_fee_local.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_unit_price
        if self.amount_unit_price:
            _dict['amount_unit_price'] = self.amount_unit_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_user
        if self.label_user:
            _dict['label_user'] = self.label_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_monetary_account
        if self.label_monetary_account:
            _dict['label_monetary_account'] = self.label_monetary_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counter_label_monetary_account
        if self.counter_label_monetary_account:
            _dict['counter_label_monetary_account'] = self.counter_label_monetary_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quote_fee
        if self.quote_fee:
            _dict['quote_fee'] = self.quote_fee.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of KrakenTransactionListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "status_description": obj.get("status_description"),
            "status_description_translated": obj.get("status_description_translated"),
            "type": obj.get("type"),
            "amount_order_source": Amount.from_dict(obj.get("amount_order_source")) if obj.get("amount_order_source") is not None else None,
            "amount_billing_source": Amount.from_dict(obj.get("amount_billing_source")) if obj.get("amount_billing_source") is not None else None,
            "amount_order_source_local": Amount.from_dict(obj.get("amount_order_source_local")) if obj.get("amount_order_source_local") is not None else None,
            "amount_billing_source_local": Amount.from_dict(obj.get("amount_billing_source_local")) if obj.get("amount_billing_source_local") is not None else None,
            "amount_order_target": Amount.from_dict(obj.get("amount_order_target")) if obj.get("amount_order_target") is not None else None,
            "amount_billing_target": Amount.from_dict(obj.get("amount_billing_target")) if obj.get("amount_billing_target") is not None else None,
            "amount_order_target_local": Amount.from_dict(obj.get("amount_order_target_local")) if obj.get("amount_order_target_local") is not None else None,
            "amount_billing_target_local": Amount.from_dict(obj.get("amount_billing_target_local")) if obj.get("amount_billing_target_local") is not None else None,
            "amount_fee": Amount.from_dict(obj.get("amount_fee")) if obj.get("amount_fee") is not None else None,
            "amount_fee_local": Amount.from_dict(obj.get("amount_fee_local")) if obj.get("amount_fee_local") is not None else None,
            "amount_unit_price": Amount.from_dict(obj.get("amount_unit_price")) if obj.get("amount_unit_price") is not None else None,
            "external_identifier": obj.get("external_identifier"),
            "label_user": LabelUser.from_dict(obj.get("label_user")) if obj.get("label_user") is not None else None,
            "label_monetary_account": LabelMonetaryAccount.from_dict(obj.get("label_monetary_account")) if obj.get("label_monetary_account") is not None else None,
            "counter_label_monetary_account": LabelMonetaryAccount.from_dict(obj.get("counter_label_monetary_account")) if obj.get("counter_label_monetary_account") is not None else None,
            "event_id": obj.get("event_id"),
            "asset_name_requested": obj.get("asset_name_requested"),
            "source": obj.get("source"),
            "quote_fee": KrakenQuoteFee.from_dict(obj.get("quote_fee")) if obj.get("quote_fee") is not None else None
        })
        return _obj


