# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.kraken_account_agreement_document import KrakenAccountAgreementDocument
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class KrakenAccountDocumentRequirementListing(BaseModel):
    """
    KrakenAccountDocumentRequirementListing
    """ # noqa: E501
    all_agreement_document: Optional[List[KrakenAccountAgreementDocument]] = Field(default=None, description="All required documents the user should accept.")
    __properties: ClassVar[List[str]] = ["all_agreement_document"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KrakenAccountDocumentRequirementListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "all_agreement_document",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in all_agreement_document (list)
        _items = []
        if self.all_agreement_document:
            for _item in self.all_agreement_document:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_agreement_document'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of KrakenAccountDocumentRequirementListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "all_agreement_document": [KrakenAccountAgreementDocument.from_dict(_item) for _item in obj.get("all_agreement_document")] if obj.get("all_agreement_document") is not None else None
        })
        return _obj


