# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LoyaltyCardListing(BaseModel):
    """
    LoyaltyCardListing
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the Loyalty Card.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the Loyalty Card's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the Loyalty Card's last update.")
    barcode: Optional[Dict[str, Any]] = None
    display_name: Optional[StrictStr] = Field(default=None, description="The display name for the loyalty card.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the loyalty card.")
    merchant_uuid: Optional[StrictStr] = Field(default=None, description="The uuid of the loyalty card merchant.")
    merchant_avatar: Optional[Dict[str, Any]] = None
    merchant_identifier: Optional[StrictStr] = Field(default=None, description="The identifier string of the loyalty card merchant")
    merchant_color: Optional[StrictStr] = Field(default=None, description="The color of the merchant")
    user_id: Optional[StrictInt] = Field(default=None, description="The id of the user owning this loyalty card.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "barcode", "display_name", "status", "merchant_uuid", "merchant_avatar", "merchant_identifier", "merchant_color", "user_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoyaltyCardListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "display_name",
                "status",
                "merchant_uuid",
                "merchant_identifier",
                "merchant_color",
                "user_id",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of barcode
        if self.barcode:
            _dict['barcode'] = self.barcode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of merchant_avatar
        if self.merchant_avatar:
            _dict['merchant_avatar'] = self.merchant_avatar.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LoyaltyCardListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "barcode": Barcode.from_dict(obj.get("barcode")) if obj.get("barcode") is not None else None,
            "display_name": obj.get("display_name"),
            "status": obj.get("status"),
            "merchant_uuid": obj.get("merchant_uuid"),
            "merchant_avatar": Avatar.from_dict(obj.get("merchant_avatar")) if obj.get("merchant_avatar") is not None else None,
            "merchant_identifier": obj.get("merchant_identifier"),
            "merchant_color": obj.get("merchant_color"),
            "user_id": obj.get("user_id")
        })
        return _obj


