# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MarketplaceAppListing(BaseModel):
    """
    MarketplaceAppListing
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="The title of the app.")
    description_short: Optional[StrictStr] = Field(default=None, description="The short description of the app.")
    description_full: Optional[StrictStr] = Field(default=None, description="The full description of the app.")
    name_developer: Optional[StrictStr] = Field(default=None, description="The developer of the app.")
    url_installation: Optional[StrictStr] = Field(default=None, description="The deeplink to install the app.")
    url_privacy_policy: Optional[StrictStr] = Field(default=None, description="The link to where the privacy policy of the app can be found.")
    url_faq: Optional[StrictStr] = Field(default=None, description="The link to where the frequently asked questions of the app can be found.")
    is_installed: Optional[StrictBool] = Field(default=None, description="If the user installed the app.")
    attachment_icon_small: Optional[Dict[str, Any]] = None
    attachment_icon_large: Optional[Dict[str, Any]] = None
    price_indication: Optional[StrictStr] = Field(default=None, description="The price of this app, as a freeform text because it can be a one-off price, monthly, yearly or free.")
    categories: Optional[List[StrictStr]] = Field(default=None, description="The categories of this app.")
    type: Optional[StrictStr] = Field(default=None, description="DEPRECATED. The type.")
    description: Optional[StrictStr] = Field(default=None, description="DEPRECATED: The description of the app.")
    url_icon: Optional[StrictStr] = Field(default=None, description="DEPRECATED. The link to the app icon.")
    url_icon_large: Optional[StrictStr] = Field(default=None, description="DEPRECATED. The link to the large app icon.")
    url_feature_banner: Optional[StrictStr] = Field(default=None, description="DEPRECATED. The link to the app banner.")
    url_together_topic: Optional[StrictStr] = Field(default=None, description="DEPRECATED. The link to together topic of this app.")
    __properties: ClassVar[List[str]] = ["title", "description_short", "description_full", "name_developer", "url_installation", "url_privacy_policy", "url_faq", "is_installed", "attachment_icon_small", "attachment_icon_large", "price_indication", "categories", "type", "description", "url_icon", "url_icon_large", "url_feature_banner", "url_together_topic"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MarketplaceAppListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "title",
                "description_short",
                "description_full",
                "name_developer",
                "url_installation",
                "url_privacy_policy",
                "url_faq",
                "is_installed",
                "price_indication",
                "categories",
                "type",
                "description",
                "url_icon",
                "url_icon_large",
                "url_feature_banner",
                "url_together_topic",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachment_icon_small
        if self.attachment_icon_small:
            _dict['attachment_icon_small'] = self.attachment_icon_small.to_dict()
        # override the default output from pydantic by calling `to_dict()` of attachment_icon_large
        if self.attachment_icon_large:
            _dict['attachment_icon_large'] = self.attachment_icon_large.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MarketplaceAppListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description_short": obj.get("description_short"),
            "description_full": obj.get("description_full"),
            "name_developer": obj.get("name_developer"),
            "url_installation": obj.get("url_installation"),
            "url_privacy_policy": obj.get("url_privacy_policy"),
            "url_faq": obj.get("url_faq"),
            "is_installed": obj.get("is_installed"),
            "attachment_icon_small": Attachment.from_dict(obj.get("attachment_icon_small")) if obj.get("attachment_icon_small") is not None else None,
            "attachment_icon_large": Attachment.from_dict(obj.get("attachment_icon_large")) if obj.get("attachment_icon_large") is not None else None,
            "price_indication": obj.get("price_indication"),
            "categories": obj.get("categories"),
            "type": obj.get("type"),
            "description": obj.get("description"),
            "url_icon": obj.get("url_icon"),
            "url_icon_large": obj.get("url_icon_large"),
            "url_feature_banner": obj.get("url_feature_banner"),
            "url_together_topic": obj.get("url_together_topic")
        })
        return _obj


