# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MasterCardClearingMessageRead(BaseModel):
    """
    MasterCardClearingMessageRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the mastercard clearing message.")
    card_id: Optional[StrictInt] = Field(default=None, description="Id of the card this clearing message is linked to.")
    mastercard_action_id: Optional[StrictInt] = Field(default=None, description="Id of the mastercard action this clearing message is linked to.")
    local_transaction_time: Optional[StrictStr] = Field(default=None, description="The local transaction time for this clearing message.")
    authorisation_id_response: Optional[StrictStr] = Field(default=None, description="The authorisation id response for this clearing message.")
    label_counterparty_display_name: Optional[StrictStr] = Field(default=None, description="The display name of the counterparty for this clearing message")
    transaction_amount: Optional[Dict[str, Any]] = None
    reconciliation_amount: Optional[Dict[str, Any]] = None
    status: Optional[StrictStr] = Field(default=None, description="The status of this clearing message.")
    message_type: Optional[StrictStr] = Field(default=None, description="The message type identifier of this clearing message")
    function_code: Optional[StrictStr] = Field(default=None, description="Together with message type describes the purpose of this clearing message.")
    message_reason_code: Optional[StrictInt] = Field(default=None, description="The message reason code for this clearing message.")
    reversal: Optional[StrictBool] = None
    city: Optional[StrictStr] = Field(default=None, description="The city where the transaction took place.")
    street: Optional[StrictStr] = Field(default=None, description="The street address where the transaction took place.")
    postal_code: Optional[StrictStr] = Field(default=None, description="The postal code where the transaction took place.")
    acquirer_reference_mixed_number: Optional[StrictStr] = Field(default=None, description="Mixed number from the acquirer reference information.")
    acquirer_reference_bin: Optional[StrictStr] = Field(default=None, description="BIN from the acquirer reference information.")
    acquirer_reference_julian_processing_date: Optional[StrictStr] = Field(default=None, description="Processing date in Julian format from the acquirer reference information.")
    acquirer_reference_sequence_number: Optional[StrictStr] = Field(default=None, description="Sequence number from the acquirer reference information.")
    acquirer_reference_check_digit: Optional[StrictStr] = Field(default=None, description="Check digit from the acquirer reference information.")
    cardholder_transaction_type: Optional[StrictStr] = Field(default=None, description="Payment, withdrawal, refund, etc.")
    __properties: ClassVar[List[str]] = ["id", "card_id", "mastercard_action_id", "local_transaction_time", "authorisation_id_response", "label_counterparty_display_name", "transaction_amount", "reconciliation_amount", "status", "message_type", "function_code", "message_reason_code", "reversal", "city", "street", "postal_code", "acquirer_reference_mixed_number", "acquirer_reference_bin", "acquirer_reference_julian_processing_date", "acquirer_reference_sequence_number", "acquirer_reference_check_digit", "cardholder_transaction_type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MasterCardClearingMessageRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "card_id",
                "mastercard_action_id",
                "local_transaction_time",
                "authorisation_id_response",
                "label_counterparty_display_name",
                "status",
                "message_type",
                "function_code",
                "message_reason_code",
                "reversal",
                "city",
                "street",
                "postal_code",
                "acquirer_reference_mixed_number",
                "acquirer_reference_bin",
                "acquirer_reference_julian_processing_date",
                "acquirer_reference_sequence_number",
                "acquirer_reference_check_digit",
                "cardholder_transaction_type",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of transaction_amount
        if self.transaction_amount:
            _dict['transaction_amount'] = self.transaction_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reconciliation_amount
        if self.reconciliation_amount:
            _dict['reconciliation_amount'] = self.reconciliation_amount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MasterCardClearingMessageRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "card_id": obj.get("card_id"),
            "mastercard_action_id": obj.get("mastercard_action_id"),
            "local_transaction_time": obj.get("local_transaction_time"),
            "authorisation_id_response": obj.get("authorisation_id_response"),
            "label_counterparty_display_name": obj.get("label_counterparty_display_name"),
            "transaction_amount": Amount.from_dict(obj.get("transaction_amount")) if obj.get("transaction_amount") is not None else None,
            "reconciliation_amount": Amount.from_dict(obj.get("reconciliation_amount")) if obj.get("reconciliation_amount") is not None else None,
            "status": obj.get("status"),
            "message_type": obj.get("message_type"),
            "function_code": obj.get("function_code"),
            "message_reason_code": obj.get("message_reason_code"),
            "reversal": obj.get("reversal"),
            "city": obj.get("city"),
            "street": obj.get("street"),
            "postal_code": obj.get("postal_code"),
            "acquirer_reference_mixed_number": obj.get("acquirer_reference_mixed_number"),
            "acquirer_reference_bin": obj.get("acquirer_reference_bin"),
            "acquirer_reference_julian_processing_date": obj.get("acquirer_reference_julian_processing_date"),
            "acquirer_reference_sequence_number": obj.get("acquirer_reference_sequence_number"),
            "acquirer_reference_check_digit": obj.get("acquirer_reference_check_digit"),
            "cardholder_transaction_type": obj.get("cardholder_transaction_type")
        })
        return _obj


