# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MasterCardTokenConnectListing(BaseModel):
    """
    MasterCardTokenConnectListing
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the model.")
    created_timestamp: Optional[StrictStr] = Field(default=None, description="When the model is created.")
    updated_timestamp: Optional[StrictStr] = Field(default=None, description="When the model is udpated.")
    requestor_id: Optional[StrictInt] = Field(default=None, description="The MasterCard Token requestor id.")
    requestor_name: Optional[StrictStr] = Field(default=None, description="The name of the MasterCard Token requestor.")
    account_range: Optional[StrictStr] = Field(default=None, description="For which account range this requestor is enabled.")
    status: Optional[StrictStr] = Field(default=None, description="Status of the requestor. Can be ACTIVE or DISABLED.")
    attachment_image: Optional[Dict[str, Any]] = None
    attachment_vector: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "created_timestamp", "updated_timestamp", "requestor_id", "requestor_name", "account_range", "status", "attachment_image", "attachment_vector"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MasterCardTokenConnectListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created_timestamp",
                "updated_timestamp",
                "requestor_id",
                "requestor_name",
                "account_range",
                "status",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachment_image
        if self.attachment_image:
            _dict['attachment_image'] = self.attachment_image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of attachment_vector
        if self.attachment_vector:
            _dict['attachment_vector'] = self.attachment_vector.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MasterCardTokenConnectListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_timestamp": obj.get("created_timestamp"),
            "updated_timestamp": obj.get("updated_timestamp"),
            "requestor_id": obj.get("requestor_id"),
            "requestor_name": obj.get("requestor_name"),
            "account_range": obj.get("account_range"),
            "status": obj.get("status"),
            "attachment_image": Attachment.from_dict(obj.get("attachment_image")) if obj.get("attachment_image") is not None else None,
            "attachment_vector": Attachment.from_dict(obj.get("attachment_vector")) if obj.get("attachment_vector") is not None else None
        })
        return _obj


