# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.pointer import Pointer
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MonetaryAccountCard(BaseModel):
    """
    MonetaryAccountCard
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the MonetaryAccountCard.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the MonetaryAccountCard's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the MonetaryAccountCard's last update.")
    currency: Optional[StrictStr] = Field(default=None, description="The currency of the MonetaryAccountCard as an ISO 4217 formatted currency code.")
    description: Optional[StrictStr] = Field(default=None, description="The description of the MonetaryAccountCard. Defaults to 'prepaid credit card'.")
    daily_limit: Optional[Dict[str, Any]] = None
    overdraft_limit: Optional[Dict[str, Any]] = None
    balance: Optional[Dict[str, Any]] = None
    balance_real: Optional[Dict[str, Any]] = None
    alias: Optional[List[Pointer]] = Field(default=None, description="The Aliases for the MonetaryAccountCard.")
    public_uuid: Optional[StrictStr] = Field(default=None, description="The MonetaryAccountCard's public UUID.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the MonetaryAccountCard.")
    sub_status: Optional[StrictStr] = Field(default=None, description="The sub-status of the MonetaryAccountCard providing extra information regarding the status.")
    user_id: Optional[StrictInt] = Field(default=None, description="The id of the User who owns the MonetaryAccountCard.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "currency", "description", "daily_limit", "overdraft_limit", "balance", "balance_real", "alias", "public_uuid", "status", "sub_status", "user_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MonetaryAccountCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "currency",
                "description",
                "alias",
                "public_uuid",
                "status",
                "sub_status",
                "user_id",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of daily_limit
        if self.daily_limit:
            _dict['daily_limit'] = self.daily_limit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of overdraft_limit
        if self.overdraft_limit:
            _dict['overdraft_limit'] = self.overdraft_limit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of balance
        if self.balance:
            _dict['balance'] = self.balance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of balance_real
        if self.balance_real:
            _dict['balance_real'] = self.balance_real.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in alias (list)
        _items = []
        if self.alias:
            for _item in self.alias:
                if _item:
                    _items.append(_item.to_dict())
            _dict['alias'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MonetaryAccountCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "currency": obj.get("currency"),
            "description": obj.get("description"),
            "daily_limit": Amount.from_dict(obj.get("daily_limit")) if obj.get("daily_limit") is not None else None,
            "overdraft_limit": Amount.from_dict(obj.get("overdraft_limit")) if obj.get("overdraft_limit") is not None else None,
            "balance": Amount.from_dict(obj.get("balance")) if obj.get("balance") is not None else None,
            "balance_real": Amount.from_dict(obj.get("balance_real")) if obj.get("balance_real") is not None else None,
            "alias": [Pointer.from_dict(_item) for _item in obj.get("alias")] if obj.get("alias") is not None else None,
            "public_uuid": obj.get("public_uuid"),
            "status": obj.get("status"),
            "sub_status": obj.get("sub_status"),
            "user_id": obj.get("user_id")
        })
        return _obj


