# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MonetaryAccountBudgetSchedule(BaseModel):
    """
    MonetaryAccountBudgetSchedule
    """ # noqa: E501
    all_category: List[StrictStr] = Field(description="The list of categories on which the user wants to set the budget.")
    amount: Dict[str, Any]
    monetary_account_remainder_id: Optional[StrictInt] = Field(default=None, description="The ID of the monetary account where to move the leftover money before topping up the monetary account.")
    recurrence_type: StrictStr = Field(description="The recurrence type for the automatic top-up.")
    monetary_account_source_funding_id: StrictInt = Field(description="The monetary account's ID from/to which the missing/exceeding funds will be transferred.")
    payment_day_of_month: Optional[StrictInt] = Field(default=None, description="The day of the month for the automatic top-up.")
    __properties: ClassVar[List[str]] = ["all_category", "amount", "monetary_account_remainder_id", "recurrence_type", "monetary_account_source_funding_id", "payment_day_of_month"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MonetaryAccountBudgetSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MonetaryAccountBudgetSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "all_category": obj.get("all_category"),
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "monetary_account_remainder_id": obj.get("monetary_account_remainder_id"),
            "recurrence_type": obj.get("recurrence_type"),
            "monetary_account_source_funding_id": obj.get("monetary_account_source_funding_id"),
            "payment_day_of_month": obj.get("payment_day_of_month")
        })
        return _obj


