# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MonetaryAccountBudgetProgress(BaseModel):
    """
    MonetaryAccountBudgetProgress
    """ # noqa: E501
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp the progress of the budget last changed.")
    amount_remaining: Optional[Dict[str, Any]] = None
    amount_spent: Optional[Dict[str, Any]] = None
    fraction_remaining: Optional[StrictStr] = Field(default=None, description="The fraction left to spend in this budget.")
    fraction_spent: Optional[StrictStr] = Field(default=None, description="The fraction spent on this budget.")
    __properties: ClassVar[List[str]] = ["updated", "amount_remaining", "amount_spent", "fraction_remaining", "fraction_spent"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MonetaryAccountBudgetProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "updated",
                "fraction_remaining",
                "fraction_spent",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_remaining
        if self.amount_remaining:
            _dict['amount_remaining'] = self.amount_remaining.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_spent
        if self.amount_spent:
            _dict['amount_spent'] = self.amount_spent.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MonetaryAccountBudgetProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "updated": obj.get("updated"),
            "amount_remaining": Amount.from_dict(obj.get("amount_remaining")) if obj.get("amount_remaining") is not None else None,
            "amount_spent": Amount.from_dict(obj.get("amount_spent")) if obj.get("amount_spent") is not None else None,
            "fraction_remaining": obj.get("fraction_remaining"),
            "fraction_spent": obj.get("fraction_spent")
        })
        return _obj


