# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NoteTextSchedulePaymentBatchRead(BaseModel):
    """
    NoteTextSchedulePaymentBatchRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the note.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the note's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the note's last update.")
    label_user_creator: Optional[Dict[str, Any]] = None
    content: Optional[StrictStr] = Field(default=None, description="The content of the note.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "label_user_creator", "content"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NoteTextSchedulePaymentBatchRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "content",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of label_user_creator
        if self.label_user_creator:
            _dict['label_user_creator'] = self.label_user_creator.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NoteTextSchedulePaymentBatchRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "label_user_creator": LabelUser.from_dict(obj.get("label_user_creator")) if obj.get("label_user_creator") is not None else None,
            "content": obj.get("content")
        })
        return _obj


