# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OpenBankingAccount(BaseModel):
    """
    OpenBankingAccount
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status of this account.")
    iban: Optional[StrictStr] = Field(default=None, description="The iban of this account.")
    time_synced_last: Optional[StrictStr] = Field(default=None, description="The timestamp of the last time the account was synced with our open banking partner.")
    provider_bank: Optional[Dict[str, Any]] = None
    balance_booked: Optional[Dict[str, Any]] = None
    balance_available: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["status", "iban", "time_synced_last", "provider_bank", "balance_booked", "balance_available"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OpenBankingAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "iban",
                "time_synced_last",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of provider_bank
        if self.provider_bank:
            _dict['provider_bank'] = self.provider_bank.to_dict()
        # override the default output from pydantic by calling `to_dict()` of balance_booked
        if self.balance_booked:
            _dict['balance_booked'] = self.balance_booked.to_dict()
        # override the default output from pydantic by calling `to_dict()` of balance_available
        if self.balance_available:
            _dict['balance_available'] = self.balance_available.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OpenBankingAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "iban": obj.get("iban"),
            "time_synced_last": obj.get("time_synced_last"),
            "provider_bank": OpenBankingProviderBank.from_dict(obj.get("provider_bank")) if obj.get("provider_bank") is not None else None,
            "balance_booked": Amount.from_dict(obj.get("balance_booked")) if obj.get("balance_booked") is not None else None,
            "balance_available": Amount.from_dict(obj.get("balance_available")) if obj.get("balance_available") is not None else None
        })
        return _obj


