# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OpenBankingAuthenticationRenewalAccountListing(BaseModel):
    """
    OpenBankingAuthenticationRenewalAccountListing
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status of the renewal request.")
    provider_bank: Optional[Dict[str, Any]] = None
    open_banking_authentication_request: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["status", "provider_bank", "open_banking_authentication_request"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OpenBankingAuthenticationRenewalAccountListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of provider_bank
        if self.provider_bank:
            _dict['provider_bank'] = self.provider_bank.to_dict()
        # override the default output from pydantic by calling `to_dict()` of open_banking_authentication_request
        if self.open_banking_authentication_request:
            _dict['open_banking_authentication_request'] = self.open_banking_authentication_request.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OpenBankingAuthenticationRenewalAccountListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "provider_bank": OpenBankingProviderBank.from_dict(obj.get("provider_bank")) if obj.get("provider_bank") is not None else None,
            "open_banking_authentication_request": OpenBankingAuthenticationRequest.from_dict(obj.get("open_banking_authentication_request")) if obj.get("open_banking_authentication_request") is not None else None
        })
        return _obj


