# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PaysafecashTransactionDepositListing(BaseModel):
    """
    PaysafecashTransactionDepositListing
    """ # noqa: E501
    monetary_account_id: Optional[StrictStr] = Field(default=None, description="The id of the monetary account chosen for this transaction.")
    status: Optional[StrictStr] = Field(default=None, description="The status.")
    sub_status: Optional[StrictStr] = Field(default=None, description="The subStatus.")
    status_paysafecash: Optional[StrictStr] = Field(default=None, description="The status as Paysafecash reports it.")
    amount: Optional[Dict[str, Any]] = None
    alias: Optional[Dict[str, Any]] = None
    paysafecash_transaction_id: Optional[StrictStr] = Field(default=None, description="The paysafecash ID of the transaction.")
    time_expiry: Optional[StrictStr] = Field(default=None, description="The time the transaction expires.")
    mutation_id: Optional[StrictInt] = Field(default=None, description="The mutation id of the transaction.")
    __properties: ClassVar[List[str]] = ["monetary_account_id", "status", "sub_status", "status_paysafecash", "amount", "alias", "paysafecash_transaction_id", "time_expiry", "mutation_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaysafecashTransactionDepositListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "monetary_account_id",
                "status",
                "sub_status",
                "status_paysafecash",
                "paysafecash_transaction_id",
                "time_expiry",
                "mutation_id",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PaysafecashTransactionDepositListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "monetary_account_id": obj.get("monetary_account_id"),
            "status": obj.get("status"),
            "sub_status": obj.get("sub_status"),
            "status_paysafecash": obj.get("status_paysafecash"),
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "alias": LabelMonetaryAccount.from_dict(obj.get("alias")) if obj.get("alias") is not None else None,
            "paysafecash_transaction_id": obj.get("paysafecash_transaction_id"),
            "time_expiry": obj.get("time_expiry"),
            "mutation_id": obj.get("mutation_id")
        })
        return _obj


