# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PointPrizeListing(BaseModel):
    """
    PointPrizeListing
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="The title of the prize.")
    description_pending: Optional[StrictStr] = Field(default=None, description="The description of the pending prize.")
    description_claimed: Optional[StrictStr] = Field(default=None, description="The description of the claimed prize.")
    button_text: Optional[StrictStr] = Field(default=None, description="Text for the button to redirect user after claiming point prize.")
    deeplink: Optional[StrictStr] = Field(default=None, description="The deeplink to guide user to the prize.")
    button_text_learn_more: Optional[StrictStr] = Field(default=None, description="The text for the button to guide user to learn more about the prize.")
    url_learn_more: Optional[StrictStr] = Field(default=None, description="The url to guide user to learn more about the prize.")
    number_of_point: Optional[StrictInt] = Field(default=None, description="The number of points you need to spend to claim this prize.")
    monitoring_limit: Optional[StrictInt] = Field(default=None, description="The limit of prizes after which monitoring should be triggered.")
    category: Optional[StrictStr] = Field(default=None, description="The category of the prize.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the prize.")
    all_country_restricted: Optional[List[StrictStr]] = Field(default=None, description="All country this prize is restricted to.")
    avatar: Optional[Dict[str, Any]] = None
    all_requirement: Optional[List[StrictStr]] = Field(default=None, description="All requirements for this prize.")
    __properties: ClassVar[List[str]] = ["title", "description_pending", "description_claimed", "button_text", "deeplink", "button_text_learn_more", "url_learn_more", "number_of_point", "monitoring_limit", "category", "status", "all_country_restricted", "avatar", "all_requirement"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PointPrizeListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "title",
                "description_pending",
                "description_claimed",
                "button_text",
                "deeplink",
                "button_text_learn_more",
                "url_learn_more",
                "number_of_point",
                "monitoring_limit",
                "category",
                "status",
                "all_country_restricted",
                "all_requirement",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of avatar
        if self.avatar:
            _dict['avatar'] = self.avatar.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PointPrizeListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description_pending": obj.get("description_pending"),
            "description_claimed": obj.get("description_claimed"),
            "button_text": obj.get("button_text"),
            "deeplink": obj.get("deeplink"),
            "button_text_learn_more": obj.get("button_text_learn_more"),
            "url_learn_more": obj.get("url_learn_more"),
            "number_of_point": obj.get("number_of_point"),
            "monitoring_limit": obj.get("monitoring_limit"),
            "category": obj.get("category"),
            "status": obj.get("status"),
            "all_country_restricted": obj.get("all_country_restricted"),
            "avatar": Avatar.from_dict(obj.get("avatar")) if obj.get("avatar") is not None else None,
            "all_requirement": obj.get("all_requirement")
        })
        return _obj


