# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.quality_assurance_test_monetary_account import QualityAssuranceTestMonetaryAccount
from openapi_server.models.tax_resident import TaxResident
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class QualityAssuranceTestUserPerson(BaseModel):
    """
    QualityAssuranceTestUserPerson
    """ # noqa: E501
    first_name: Optional[StrictStr] = Field(default=None, description="The first name of the user.")
    last_name: Optional[StrictStr] = Field(default=None, description="The last name of the user.")
    gender: Optional[StrictStr] = Field(default=None, description="The gender of the user.")
    vital_status: Optional[StrictStr] = Field(default=None, description="The vital status of the user.")
    date_of_birth: Optional[StrictStr] = Field(default=None, description="The date of birth of the user.")
    age: Optional[StrictInt] = Field(default=None, description="The age of the user.")
    country_of_birth: Optional[StrictStr] = Field(default=None, description="The country of birth of the user.")
    city_of_birth: Optional[StrictStr] = Field(default=None, description="The city of birth of the user.")
    postal_code_of_birth: Optional[StrictStr] = Field(default=None, description="The postal code of birth of the user.")
    all_monetary_account_definition: Optional[List[QualityAssuranceTestMonetaryAccount]] = Field(default=None, description="All monetary accounts for the user.")
    all_nationality: Optional[List[StrictStr]] = Field(default=None, description="The nationalities of the user.")
    all_tax_identification_number: Optional[List[TaxResident]] = Field(default=None, description="The tax identification numbers of the user.")
    country: Optional[StrictStr] = Field(default=None, description="The country of the user.")
    country_of_banking_license: Optional[StrictStr] = Field(default=None, description="The country of banking license of the user.")
    language: Optional[StrictStr] = Field(default=None, description="The language of the user.")
    region: Optional[StrictStr] = Field(default=None, description="The region of the user.")
    city: Optional[StrictStr] = Field(default=None, description="The city of the user.")
    address_main: Optional[Dict[str, Any]] = None
    address_postal: Optional[Dict[str, Any]] = None
    display_name: Optional[StrictStr] = Field(default=None, description="The display name of the user.")
    public_nick_name: Optional[StrictStr] = Field(default=None, description="The public nick name of the user.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the user.")
    sub_status: Optional[StrictStr] = Field(default=None, description="The sub status of the user.")
    initial_balance: Optional[StrictInt] = Field(default=None, description="The initial balance of the user.")
    phone_number: Optional[StrictStr] = Field(default=None, description="The phone number of the user.")
    email: Optional[StrictStr] = Field(default=None, description="The email of the user.")
    all_billing_subscription_type: Optional[List[StrictStr]] = Field(default=None, description="The all billing subscription type of the user.")
    risk_fraud_label: Optional[StrictStr] = Field(default=None, description="The risk fraud label of the user.")
    risk_score: Optional[StrictStr] = Field(default=None, description="The risk score of the user.")
    currency: Optional[StrictStr] = Field(default=None, description="The currency of the user.")
    interest_preference_receive_interest: Optional[StrictStr] = Field(default=None, description="The interest preference receive interest of the user.")
    all_investment_type: Optional[List[StrictStr]] = Field(default=None, description="The all investment type of the user.")
    login_code: Optional[StrictStr] = Field(default=None, description="The login code of the user.")
    setting_communication_marketing: Optional[StrictStr] = Field(default=None, description="The setting communication marketing of the user.")
    approval_status: Optional[StrictStr] = Field(default=None, description="The approval status of the user.")
    verification_status: Optional[StrictStr] = Field(default=None, description="The verification status of the user.")
    time_user_creation: Optional[StrictStr] = Field(default=None, description="The time user creation of the user.")
    all_tag_user: Optional[List[StrictStr]] = Field(default=None, description="The all tag user of the user.")
    should_create_user_visited_ip: Optional[StrictBool] = Field(default=None, description="Should a UserVisitedIp be created for the user (requires `ip` to be set.)")
    should_create_credential: Optional[StrictBool] = Field(default=None, description="The should create credential of the user.")
    should_create_all_identification_document: Optional[StrictBool] = Field(default=None, description="The should create all identification document of the user.")
    identification_document_type: Optional[StrictStr] = Field(default=None, description="The identification document type of the user.")
    identification_document_number: Optional[StrictStr] = Field(default=None, description="The identification document number of the user.")
    identification_document_date_expiry: Optional[StrictStr] = Field(default=None, description="The identification document date expiry of the user.")
    identification_document_country: Optional[StrictStr] = Field(default=None, description="The identification document country of the user.")
    should_create_all_notification_filter: Optional[StrictBool] = Field(default=None, description="The should create all notification filter of the user.")
    should_complete_invite: Optional[StrictBool] = Field(default=None, description="The should complete invite of the user.")
    should_create_flarum_user_profile: Optional[StrictBool] = Field(default=None, description="The should create flarum user profile of the user.")
    should_sync_fulfillment: Optional[StrictBool] = Field(default=None, description="The should sync fulfillment of the user.")
    should_create_alias_email: Optional[StrictBool] = Field(default=None, description="The should create alias email of the user.")
    should_create_alias_phone_number: Optional[StrictBool] = Field(default=None, description="The should create alias phone number of the user.")
    should_create_address_main: Optional[StrictBool] = Field(default=None, description="The should create address main of the user.")
    should_create_address_postal: Optional[StrictBool] = Field(default=None, description="The should create address postal of the user.")
    should_create_risk_information: Optional[StrictBool] = Field(default=None, description="The should create risk information of the user.")
    should_create_video_onboarding: Optional[StrictBool] = Field(default=None, description="The should create video onboarding of the user.")
    should_create_branch_switch: Optional[StrictBool] = Field(default=None, description="The should create branch switch of the user.")
    should_create_user_identification_verification: Optional[StrictBool] = Field(default=None, description="The should create identification verification of the user.")
    should_create_all_identification_attachment: Optional[StrictBool] = Field(default=None, description="The should create identification verification attachment of the user.")
    should_create_identity_verification: Optional[StrictBool] = Field(default=None, description="The should create identity verification of the user.")
    should_create_support_user_validation: Optional[StrictBool] = Field(default=None, description="Whether we should create a support user validation for the user.")
    setting_zero_fx: Optional[StrictStr] = Field(default=None, description="The setting zero fx of the user.")
    setting_local_currency: Optional[StrictStr] = Field(default=None, description="The setting local currency of the user.")
    setting_card_country_permission_auto_select: Optional[StrictStr] = Field(default=None, description="The setting for automatic card country permission selection.")
    device_definition: Optional[Dict[str, Any]] = None
    marital_status_type: Optional[StrictStr] = Field(default=None, description="The marital status of the user.")
    income_source_type: Optional[StrictStr] = Field(default=None, description="The source of income of the user.")
    living_situation_type: Optional[StrictStr] = Field(default=None, description="The living situation of the user.")
    employment_status_type: Optional[StrictStr] = Field(default=None, description="The employment status of the user.")
    all_user_exposure: Optional[StrictStr] = Field(default=None, description="The exposure of the user")
    __properties: ClassVar[List[str]] = ["first_name", "last_name", "gender", "vital_status", "date_of_birth", "age", "country_of_birth", "city_of_birth", "postal_code_of_birth", "all_monetary_account_definition", "all_nationality", "all_tax_identification_number", "country", "country_of_banking_license", "language", "region", "city", "address_main", "address_postal", "display_name", "public_nick_name", "status", "sub_status", "initial_balance", "phone_number", "email", "all_billing_subscription_type", "risk_fraud_label", "risk_score", "currency", "interest_preference_receive_interest", "all_investment_type", "login_code", "setting_communication_marketing", "approval_status", "verification_status", "time_user_creation", "all_tag_user", "should_create_user_visited_ip", "should_create_credential", "should_create_all_identification_document", "identification_document_type", "identification_document_number", "identification_document_date_expiry", "identification_document_country", "should_create_all_notification_filter", "should_complete_invite", "should_create_flarum_user_profile", "should_sync_fulfillment", "should_create_alias_email", "should_create_alias_phone_number", "should_create_address_main", "should_create_address_postal", "should_create_risk_information", "should_create_video_onboarding", "should_create_branch_switch", "should_create_user_identification_verification", "should_create_all_identification_attachment", "should_create_identity_verification", "should_create_support_user_validation", "setting_zero_fx", "setting_local_currency", "setting_card_country_permission_auto_select", "device_definition", "marital_status_type", "income_source_type", "living_situation_type", "employment_status_type", "all_user_exposure"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QualityAssuranceTestUserPerson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in all_monetary_account_definition (list)
        _items = []
        if self.all_monetary_account_definition:
            for _item in self.all_monetary_account_definition:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_monetary_account_definition'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in all_tax_identification_number (list)
        _items = []
        if self.all_tax_identification_number:
            for _item in self.all_tax_identification_number:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_tax_identification_number'] = _items
        # override the default output from pydantic by calling `to_dict()` of address_main
        if self.address_main:
            _dict['address_main'] = self.address_main.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address_postal
        if self.address_postal:
            _dict['address_postal'] = self.address_postal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of device_definition
        if self.device_definition:
            _dict['device_definition'] = self.device_definition.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of QualityAssuranceTestUserPerson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "gender": obj.get("gender"),
            "vital_status": obj.get("vital_status"),
            "date_of_birth": obj.get("date_of_birth"),
            "age": obj.get("age"),
            "country_of_birth": obj.get("country_of_birth"),
            "city_of_birth": obj.get("city_of_birth"),
            "postal_code_of_birth": obj.get("postal_code_of_birth"),
            "all_monetary_account_definition": [QualityAssuranceTestMonetaryAccount.from_dict(_item) for _item in obj.get("all_monetary_account_definition")] if obj.get("all_monetary_account_definition") is not None else None,
            "all_nationality": obj.get("all_nationality"),
            "all_tax_identification_number": [TaxResident.from_dict(_item) for _item in obj.get("all_tax_identification_number")] if obj.get("all_tax_identification_number") is not None else None,
            "country": obj.get("country"),
            "country_of_banking_license": obj.get("country_of_banking_license"),
            "language": obj.get("language"),
            "region": obj.get("region"),
            "city": obj.get("city"),
            "address_main": Address.from_dict(obj.get("address_main")) if obj.get("address_main") is not None else None,
            "address_postal": Address.from_dict(obj.get("address_postal")) if obj.get("address_postal") is not None else None,
            "display_name": obj.get("display_name"),
            "public_nick_name": obj.get("public_nick_name"),
            "status": obj.get("status"),
            "sub_status": obj.get("sub_status"),
            "initial_balance": obj.get("initial_balance"),
            "phone_number": obj.get("phone_number"),
            "email": obj.get("email"),
            "all_billing_subscription_type": obj.get("all_billing_subscription_type"),
            "risk_fraud_label": obj.get("risk_fraud_label"),
            "risk_score": obj.get("risk_score"),
            "currency": obj.get("currency"),
            "interest_preference_receive_interest": obj.get("interest_preference_receive_interest"),
            "all_investment_type": obj.get("all_investment_type"),
            "login_code": obj.get("login_code"),
            "setting_communication_marketing": obj.get("setting_communication_marketing"),
            "approval_status": obj.get("approval_status"),
            "verification_status": obj.get("verification_status"),
            "time_user_creation": obj.get("time_user_creation"),
            "all_tag_user": obj.get("all_tag_user"),
            "should_create_user_visited_ip": obj.get("should_create_user_visited_ip"),
            "should_create_credential": obj.get("should_create_credential"),
            "should_create_all_identification_document": obj.get("should_create_all_identification_document"),
            "identification_document_type": obj.get("identification_document_type"),
            "identification_document_number": obj.get("identification_document_number"),
            "identification_document_date_expiry": obj.get("identification_document_date_expiry"),
            "identification_document_country": obj.get("identification_document_country"),
            "should_create_all_notification_filter": obj.get("should_create_all_notification_filter"),
            "should_complete_invite": obj.get("should_complete_invite"),
            "should_create_flarum_user_profile": obj.get("should_create_flarum_user_profile"),
            "should_sync_fulfillment": obj.get("should_sync_fulfillment"),
            "should_create_alias_email": obj.get("should_create_alias_email"),
            "should_create_alias_phone_number": obj.get("should_create_alias_phone_number"),
            "should_create_address_main": obj.get("should_create_address_main"),
            "should_create_address_postal": obj.get("should_create_address_postal"),
            "should_create_risk_information": obj.get("should_create_risk_information"),
            "should_create_video_onboarding": obj.get("should_create_video_onboarding"),
            "should_create_branch_switch": obj.get("should_create_branch_switch"),
            "should_create_user_identification_verification": obj.get("should_create_user_identification_verification"),
            "should_create_all_identification_attachment": obj.get("should_create_all_identification_attachment"),
            "should_create_identity_verification": obj.get("should_create_identity_verification"),
            "should_create_support_user_validation": obj.get("should_create_support_user_validation"),
            "setting_zero_fx": obj.get("setting_zero_fx"),
            "setting_local_currency": obj.get("setting_local_currency"),
            "setting_card_country_permission_auto_select": obj.get("setting_card_country_permission_auto_select"),
            "device_definition": QualityAssuranceTestDevice.from_dict(obj.get("device_definition")) if obj.get("device_definition") is not None else None,
            "marital_status_type": obj.get("marital_status_type"),
            "income_source_type": obj.get("income_source_type"),
            "living_situation_type": obj.get("living_situation_type"),
            "employment_status_type": obj.get("employment_status_type"),
            "all_user_exposure": obj.get("all_user_exposure")
        })
        return _obj


