# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.attachment import Attachment
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RegistryChatMessageRead(BaseModel):
    """
    RegistryChatMessageRead
    """ # noqa: E501
    label_user: Optional[Dict[str, Any]] = None
    is_posted_by_membership_current: Optional[StrictBool] = Field(default=None, description="Indicator of whether or not the chat message was posted by the membership associated with the current user, to help apps with the display.")
    text: Optional[StrictStr] = Field(default=None, description="The textual content of this message.")
    attachment: Optional[List[Attachment]] = Field(default=None, description="The attachments attached to the chat message.")
    __properties: ClassVar[List[str]] = ["label_user", "is_posted_by_membership_current", "text", "attachment"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RegistryChatMessageRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "is_posted_by_membership_current",
                "text",
                "attachment",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of label_user
        if self.label_user:
            _dict['label_user'] = self.label_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attachment (list)
        _items = []
        if self.attachment:
            for _item in self.attachment:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attachment'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RegistryChatMessageRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "label_user": LabelUser.from_dict(obj.get("label_user")) if obj.get("label_user") is not None else None,
            "is_posted_by_membership_current": obj.get("is_posted_by_membership_current"),
            "text": obj.get("text"),
            "attachment": [Attachment.from_dict(_item) for _item in obj.get("attachment")] if obj.get("attachment") is not None else None
        })
        return _obj


