# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.registry_membership import RegistryMembership
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RegistryPublicListing(BaseModel):
    """
    RegistryPublicListing
    """ # noqa: E501
    public_identifier_token: Optional[StrictStr] = Field(default=None, description="Public identifier token provided by the client. Will remain null if not provided in the POST call.")
    registry_uuid: Optional[StrictStr] = Field(default=None, description="The uuid of the Registry. If it was provided by the client on creation, then the client can use it to match the returned Registry to the row stored locally.")
    currency: Optional[StrictStr] = Field(default=None, description="The currency for the Registry as an ISO 4217 formatted currency code.")
    emoji: Optional[StrictStr] = Field(default=None, description="The emoji of the registry.")
    title: Optional[StrictStr] = Field(default=None, description="The title of the Registry.")
    description: Optional[StrictStr] = Field(default=None, description="A description about the Registry.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the Registry.")
    all_membership: Optional[List[RegistryMembership]] = Field(default=None, description="All registry memberships belong to a Registry.")
    __properties: ClassVar[List[str]] = ["public_identifier_token", "registry_uuid", "currency", "emoji", "title", "description", "status", "all_membership"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RegistryPublicListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "public_identifier_token",
                "registry_uuid",
                "currency",
                "emoji",
                "title",
                "description",
                "status",
                "all_membership",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in all_membership (list)
        _items = []
        if self.all_membership:
            for _item in self.all_membership:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_membership'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RegistryPublicListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "public_identifier_token": obj.get("public_identifier_token"),
            "registry_uuid": obj.get("registry_uuid"),
            "currency": obj.get("currency"),
            "emoji": obj.get("emoji"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "all_membership": [RegistryMembership.from_dict(_item) for _item in obj.get("all_membership")] if obj.get("all_membership") is not None else None
        })
        return _obj


