# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RequestReferenceSplitTheBillAnchorObject(BaseModel):
    """
    RequestReferenceSplitTheBillAnchorObject
    """ # noqa: E501
    billing_invoice: Optional[Dict[str, Any]] = Field(default=None, alias="BillingInvoice")
    draft_payment: Optional[Dict[str, Any]] = Field(default=None, alias="DraftPayment")
    master_card_action: Optional[Dict[str, Any]] = Field(default=None, alias="MasterCardAction")
    payment: Optional[Dict[str, Any]] = Field(default=None, alias="Payment")
    payment_batch: Optional[Dict[str, Any]] = Field(default=None, alias="PaymentBatch")
    request_response: Optional[Dict[str, Any]] = Field(default=None, alias="RequestResponse")
    schedule_instance: Optional[Dict[str, Any]] = Field(default=None, alias="ScheduleInstance")
    whitelist_result: Optional[Dict[str, Any]] = Field(default=None, alias="WhitelistResult")
    transferwise_payment: Optional[Dict[str, Any]] = Field(default=None, alias="TransferwisePayment")
    currency_conversion: Optional[Dict[str, Any]] = Field(default=None, alias="CurrencyConversion")
    __properties: ClassVar[List[str]] = ["BillingInvoice", "DraftPayment", "MasterCardAction", "Payment", "PaymentBatch", "RequestResponse", "ScheduleInstance", "WhitelistResult", "TransferwisePayment", "CurrencyConversion"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RequestReferenceSplitTheBillAnchorObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of billing_invoice
        if self.billing_invoice:
            _dict['BillingInvoice'] = self.billing_invoice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of draft_payment
        if self.draft_payment:
            _dict['DraftPayment'] = self.draft_payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of master_card_action
        if self.master_card_action:
            _dict['MasterCardAction'] = self.master_card_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment
        if self.payment:
            _dict['Payment'] = self.payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_batch
        if self.payment_batch:
            _dict['PaymentBatch'] = self.payment_batch.to_dict()
        # override the default output from pydantic by calling `to_dict()` of request_response
        if self.request_response:
            _dict['RequestResponse'] = self.request_response.to_dict()
        # override the default output from pydantic by calling `to_dict()` of schedule_instance
        if self.schedule_instance:
            _dict['ScheduleInstance'] = self.schedule_instance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of whitelist_result
        if self.whitelist_result:
            _dict['WhitelistResult'] = self.whitelist_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transferwise_payment
        if self.transferwise_payment:
            _dict['TransferwisePayment'] = self.transferwise_payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of currency_conversion
        if self.currency_conversion:
            _dict['CurrencyConversion'] = self.currency_conversion.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RequestReferenceSplitTheBillAnchorObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "BillingInvoice": Invoice.from_dict(obj.get("BillingInvoice")) if obj.get("BillingInvoice") is not None else None,
            "DraftPayment": DraftPayment.from_dict(obj.get("DraftPayment")) if obj.get("DraftPayment") is not None else None,
            "MasterCardAction": MasterCardAction.from_dict(obj.get("MasterCardAction")) if obj.get("MasterCardAction") is not None else None,
            "Payment": Payment.from_dict(obj.get("Payment")) if obj.get("Payment") is not None else None,
            "PaymentBatch": PaymentBatch.from_dict(obj.get("PaymentBatch")) if obj.get("PaymentBatch") is not None else None,
            "RequestResponse": RequestResponse.from_dict(obj.get("RequestResponse")) if obj.get("RequestResponse") is not None else None,
            "ScheduleInstance": ScheduleInstance.from_dict(obj.get("ScheduleInstance")) if obj.get("ScheduleInstance") is not None else None,
            "WhitelistResult": WhitelistResult.from_dict(obj.get("WhitelistResult")) if obj.get("WhitelistResult") is not None else None,
            "TransferwisePayment": TransferwiseTransfer.from_dict(obj.get("TransferwisePayment")) if obj.get("TransferwisePayment") is not None else None,
            "CurrencyConversion": CurrencyConversion.from_dict(obj.get("CurrencyConversion")) if obj.get("CurrencyConversion") is not None else None
        })
        return _obj


