# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RiskBehaviorCheckBlocklist(BaseModel):
    """
    RiskBehaviorCheckBlocklist
    """ # noqa: E501
    external_model_name: StrictStr = Field(description="The name of the external model we are blocklisting.")
    external_model_id: StrictInt = Field(description="The id of the external model we are blocklisting.")
    comment: StrictStr = Field(description="The comment on why this blocklist is created.")
    time_expiry: StrictStr = Field(description="The time at which the block of this risk behavior check blocklist expires.")
    status: StrictStr = Field(description="The status with which we should update the blocklist.")
    __properties: ClassVar[List[str]] = ["external_model_name", "external_model_id", "comment", "time_expiry", "status"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RiskBehaviorCheckBlocklist from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RiskBehaviorCheckBlocklist from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_model_name": obj.get("external_model_name"),
            "external_model_id": obj.get("external_model_id"),
            "comment": obj.get("comment"),
            "time_expiry": obj.get("time_expiry"),
            "status": obj.get("status")
        })
        return _obj


