# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SavingsAutoSaveListing(BaseModel):
    """
    SavingsAutoSaveListing
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the SavingsAutoSave.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp when the SavingsAutoSave was created.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp when the SavingsAutoSave was last updated.")
    alias_monetary_account: Optional[Dict[str, Any]] = None
    status: Optional[StrictStr] = Field(default=None, description="The status of the SavingsAutoSave.")
    round_to: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "alias_monetary_account", "status", "round_to"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SavingsAutoSaveListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "status",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alias_monetary_account
        if self.alias_monetary_account:
            _dict['alias_monetary_account'] = self.alias_monetary_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of round_to
        if self.round_to:
            _dict['round_to'] = self.round_to.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SavingsAutoSaveListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "alias_monetary_account": LabelMonetaryAccount.from_dict(obj.get("alias_monetary_account")) if obj.get("alias_monetary_account") is not None else None,
            "status": obj.get("status"),
            "round_to": Amount.from_dict(obj.get("round_to")) if obj.get("round_to") is not None else None
        })
        return _obj


