# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SddDebitIncomingRead(BaseModel):
    """
    SddDebitIncomingRead
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status of the incoming SDD. Can be WAITING_FOR_HANDLING, PENDING_SETTLEMENT, SETTLED, PAYMENT_REQUESTED_PENDING_RESPONSE, PAID, REFUSED_PENDING_SENDING, REFUSED_SENT, REJECTED_PENDING_SENDING, REJECTED_SENT, CANCELLED, RETURNED_AFTER_PAYMENT_PENDING_SENDING, RETURNED_AFTER_PAYMENT_PENDING_SETTLEMENT, RETURNED_AFTER_PAYMENT_SETTLED, RETURNED_BEFORE_PAYMENT_PENDING_SENDING, RETURNED_BEFORE_PAYMENT_PENDING_SETTLEMENT, RETURNED_BEFORE_PAYMENT_SETTLED, REVERSED_AFTER_PAYMENT_PENDING_SETTLEMENT, REVERSED_AFTER_PAYMENT_SETTLED, REVERSED_BEFORE_PAYMENT_PENDING_SETTLEMENT, REVERSED_BEFORE_PAYMENT_SETTLED.")
    due_date: Optional[StrictStr] = Field(default=None, description="The date the debit is due.")
    inter_bank_settlement_date: Optional[StrictStr] = Field(default=None, description="The date the debit gets settled by EBA through TARGET2. Equal to due date if this is a TARGET2 date, otherwise next TARGET2 date.")
    mandate_identifier: Optional[StrictStr] = Field(default=None, description="The mandate id.")
    mandate_signature_date: Optional[StrictStr] = Field(default=None, description="The mandate signature's date.")
    money_amount: Optional[Dict[str, Any]] = None
    creditor: Optional[Dict[str, Any]] = None
    debtor: Optional[Dict[str, Any]] = None
    description: Optional[StrictStr] = Field(default=None, description="Unstructured Remittance Information, or simply the description.")
    settlement_mutation_id: Optional[StrictInt] = Field(default=None, description="The corresponding mutation on the settlement MonetaryAccount.")
    request_inquiry_id: Optional[StrictInt] = Field(default=None, description="The request inquiry for this direct debit.")
    request_response_id: Optional[StrictInt] = Field(default=None, description="The request response for this direct debit.")
    __properties: ClassVar[List[str]] = ["status", "due_date", "inter_bank_settlement_date", "mandate_identifier", "mandate_signature_date", "money_amount", "creditor", "debtor", "description", "settlement_mutation_id", "request_inquiry_id", "request_response_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SddDebitIncomingRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "due_date",
                "inter_bank_settlement_date",
                "mandate_identifier",
                "mandate_signature_date",
                "description",
                "settlement_mutation_id",
                "request_inquiry_id",
                "request_response_id",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of money_amount
        if self.money_amount:
            _dict['money_amount'] = self.money_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of creditor
        if self.creditor:
            _dict['creditor'] = self.creditor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of debtor
        if self.debtor:
            _dict['debtor'] = self.debtor.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SddDebitIncomingRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "due_date": obj.get("due_date"),
            "inter_bank_settlement_date": obj.get("inter_bank_settlement_date"),
            "mandate_identifier": obj.get("mandate_identifier"),
            "mandate_signature_date": obj.get("mandate_signature_date"),
            "money_amount": Amount.from_dict(obj.get("money_amount")) if obj.get("money_amount") is not None else None,
            "creditor": SddDebitIncomingParty.from_dict(obj.get("creditor")) if obj.get("creditor") is not None else None,
            "debtor": SddDebitIncomingParty.from_dict(obj.get("debtor")) if obj.get("debtor") is not None else None,
            "description": obj.get("description"),
            "settlement_mutation_id": obj.get("settlement_mutation_id"),
            "request_inquiry_id": obj.get("request_inquiry_id"),
            "request_response_id": obj.get("request_response_id")
        })
        return _obj


