# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SupportEmailForwardingRule(BaseModel):
    """
    SupportEmailForwardingRule
    """ # noqa: E501
    destination_email: StrictStr = Field(description="The email address the incoming emails matching the rules should be forwarded to.")
    destination_name: StrictStr = Field(description="The name of the receiving department or person.")
    sender_email: Optional[StrictStr] = Field(default=None, description="The email address which the email to be forwarded was sent from. Required if no sender domain or local partis provided.")
    sender_email_local_part: Optional[StrictStr] = Field(default=None, description="The local part of the email which the email to be forwarded was sent from. Required if no sender domain or email is provided.")
    sender_domain: Optional[StrictStr] = Field(default=None, description="The domain the email to be forwarded was sent from. Required if no sender email or local part is provided.")
    status: StrictStr = Field(description="The status of the rule (ACTIVE/INACTIVE).")
    description: Optional[StrictStr] = Field(default=None, description="An optional description.")
    __properties: ClassVar[List[str]] = ["destination_email", "destination_name", "sender_email", "sender_email_local_part", "sender_domain", "status", "description"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupportEmailForwardingRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SupportEmailForwardingRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destination_email": obj.get("destination_email"),
            "destination_name": obj.get("destination_name"),
            "sender_email": obj.get("sender_email"),
            "sender_email_local_part": obj.get("sender_email_local_part"),
            "sender_domain": obj.get("sender_domain"),
            "status": obj.get("status"),
            "description": obj.get("description")
        })
        return _obj


