# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SupportUserRatingRator(BaseModel):
    """
    SupportUserRatingRator
    """ # noqa: E501
    rating: StrictStr = Field(description="The rating's number of stars.")
    comment: Optional[StrictStr] = Field(default=None, description="Comment explaining the rating.")
    all_skill_improvement: Optional[List[StrictStr]] = Field(default=None, description="Explains what skills could be improved. Deprecating this once app only return support_review.")
    support_feedback: Optional[StrictStr] = Field(default=None, description="Eva's feedback for the ticket guide.")
    __properties: ClassVar[List[str]] = ["rating", "comment", "all_skill_improvement", "support_feedback"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupportUserRatingRator from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SupportUserRatingRator from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rating": obj.get("rating"),
            "comment": obj.get("comment"),
            "all_skill_improvement": obj.get("all_skill_improvement"),
            "support_feedback": obj.get("support_feedback")
        })
        return _obj


