# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.savings_auto_save_entry import SavingsAutoSaveEntry
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TransferwiseTransferRead(BaseModel):
    """
    TransferwiseTransferRead
    """ # noqa: E501
    alias: Optional[Dict[str, Any]] = None
    counterparty_alias: Optional[Dict[str, Any]] = None
    status: Optional[StrictStr] = Field(default=None, description="The status.")
    sub_status: Optional[StrictStr] = Field(default=None, description="The subStatus.")
    status_transferwise: Optional[StrictStr] = Field(default=None, description="The status as Transferwise reports it.")
    status_transferwise_issue: Optional[StrictStr] = Field(default=None, description="A status to indicatie if Transferwise has an issue with this payment and requires more information.")
    amount_source: Optional[Dict[str, Any]] = None
    amount_target: Optional[Dict[str, Any]] = None
    rate: Optional[StrictStr] = Field(default=None, description="The rate of the payment.")
    reference: Optional[StrictStr] = Field(default=None, description="The reference of the payment.")
    pay_in_reference: Optional[StrictStr] = Field(default=None, description="The Pay-In reference of the payment.")
    time_delivery_estimate: Optional[StrictStr] = Field(default=None, description="The estimated delivery time.")
    quote: Optional[Dict[str, Any]] = None
    all_auto_save_entry: Optional[List[SavingsAutoSaveEntry]] = Field(default=None, description="A reference to the AutoSaveEntries if they exist.")
    __properties: ClassVar[List[str]] = ["alias", "counterparty_alias", "status", "sub_status", "status_transferwise", "status_transferwise_issue", "amount_source", "amount_target", "rate", "reference", "pay_in_reference", "time_delivery_estimate", "quote", "all_auto_save_entry"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransferwiseTransferRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "sub_status",
                "status_transferwise",
                "status_transferwise_issue",
                "rate",
                "reference",
                "pay_in_reference",
                "time_delivery_estimate",
                "all_auto_save_entry",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counterparty_alias
        if self.counterparty_alias:
            _dict['counterparty_alias'] = self.counterparty_alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_source
        if self.amount_source:
            _dict['amount_source'] = self.amount_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_target
        if self.amount_target:
            _dict['amount_target'] = self.amount_target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quote
        if self.quote:
            _dict['quote'] = self.quote.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in all_auto_save_entry (list)
        _items = []
        if self.all_auto_save_entry:
            for _item in self.all_auto_save_entry:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_auto_save_entry'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TransferwiseTransferRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alias": LabelMonetaryAccount.from_dict(obj.get("alias")) if obj.get("alias") is not None else None,
            "counterparty_alias": LabelMonetaryAccount.from_dict(obj.get("counterparty_alias")) if obj.get("counterparty_alias") is not None else None,
            "status": obj.get("status"),
            "sub_status": obj.get("sub_status"),
            "status_transferwise": obj.get("status_transferwise"),
            "status_transferwise_issue": obj.get("status_transferwise_issue"),
            "amount_source": Amount.from_dict(obj.get("amount_source")) if obj.get("amount_source") is not None else None,
            "amount_target": Amount.from_dict(obj.get("amount_target")) if obj.get("amount_target") is not None else None,
            "rate": obj.get("rate"),
            "reference": obj.get("reference"),
            "pay_in_reference": obj.get("pay_in_reference"),
            "time_delivery_estimate": obj.get("time_delivery_estimate"),
            "quote": TransferwiseQuote.from_dict(obj.get("quote")) if obj.get("quote") is not None else None,
            "all_auto_save_entry": [SavingsAutoSaveEntry.from_dict(_item) for _item in obj.get("all_auto_save_entry")] if obj.get("all_auto_save_entry") is not None else None
        })
        return _obj


