# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.error_inner import ErrorInner
from openapi_server.models.translink_transaction_entry import TranslinkTransactionEntry
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TranslinkTransactionListing(BaseModel):
    """
    TranslinkTransactionListing
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="Type of transaction, can be TRIP, REFUND, WITHDRAWAL or TOP_UP.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the transaction. Can be CREATED, SETTLED or FAILED.")
    failure_reason: Optional[List[List[ErrorInner]]] = Field(default=None, description="The reason why the transaction FAILED processing.")
    payments: Optional[Dict[str, Any]] = None
    entries: Optional[List[TranslinkTransactionEntry]] = Field(default=None, description="The list of entries in the transaction.")
    amount: Optional[Dict[str, Any]] = None
    alias: Optional[Dict[str, Any]] = None
    reference: Optional[StrictStr] = Field(default=None, description="The request reference.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the payment request.")
    __properties: ClassVar[List[str]] = ["type", "status", "failure_reason", "payments", "entries", "amount", "alias", "reference", "description"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TranslinkTransactionListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "type",
                "status",
                "failure_reason",
                "entries",
                "reference",
                "description",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in failure_reason (list of list)
        _items = []
        if self.failure_reason:
            for _item in self.failure_reason:
                if _item:
                    _items.append(
                         [_inner_item.to_dict() for _inner_item in _item if _inner_item is not None]
                    )
            _dict['failure_reason'] = _items
        # override the default output from pydantic by calling `to_dict()` of payments
        if self.payments:
            _dict['payments'] = self.payments.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in entries (list)
        _items = []
        if self.entries:
            for _item in self.entries:
                if _item:
                    _items.append(_item.to_dict())
            _dict['entries'] = _items
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TranslinkTransactionListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "status": obj.get("status"),
            "failure_reason": [
                    [ErrorInner.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj.get("failure_reason")
                ] if obj.get("failure_reason") is not None else None,
            "payments": PaymentBatchAnchoredPayment.from_dict(obj.get("payments")) if obj.get("payments") is not None else None,
            "entries": [TranslinkTransactionEntry.from_dict(_item) for _item in obj.get("entries")] if obj.get("entries") is not None else None,
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "alias": LabelMonetaryAccount.from_dict(obj.get("alias")) if obj.get("alias") is not None else None,
            "reference": obj.get("reference"),
            "description": obj.get("description")
        })
        return _obj


