# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TranslinkSettlementReportRead(BaseModel):
    """
    TranslinkSettlementReportRead
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status of the settlement report. Can be CREATED, GENERATED or FAILED.")
    type: Optional[StrictStr] = Field(default=None, description="The type of the settlement report. Can be OPERATOR, TRIP or RETAILER.")
    file_name: Optional[StrictStr] = Field(default=None, description="The name of the file.")
    amount: Optional[Dict[str, Any]] = None
    hash: Optional[StrictStr] = Field(default=None, description="hash checksum of the report content.")
    date_settlement: Optional[StrictStr] = Field(default=None, description="The settlement date the report is generated for.")
    label_user: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["status", "type", "file_name", "amount", "hash", "date_settlement", "label_user"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TranslinkSettlementReportRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "type",
                "file_name",
                "hash",
                "date_settlement",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of label_user
        if self.label_user:
            _dict['label_user'] = self.label_user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TranslinkSettlementReportRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "type": obj.get("type"),
            "file_name": obj.get("file_name"),
            "amount": Amount.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "hash": obj.get("hash"),
            "date_settlement": obj.get("date_settlement"),
            "label_user": LabelUser.from_dict(obj.get("label_user")) if obj.get("label_user") is not None else None
        })
        return _obj


