# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TravelInsurancePolicyListing(BaseModel):
    """
    TravelInsurancePolicyListing
    """ # noqa: E501
    policy_number: Optional[StrictStr] = Field(default=None, description="Number of this policy.")
    user_creator: Optional[Dict[str, Any]] = None
    user_insured: Optional[Dict[str, Any]] = None
    status: Optional[StrictStr] = Field(default=None, description="Status of the insurance policy.")
    reason_cancel: Optional[StrictStr] = Field(default=None, description="The reason why this policy was cancelled, if status is CANCELLED, otherwise null.")
    country: Optional[StrictStr] = Field(default=None, description="Country this insurance policy is issued at.")
    claim_url: Optional[StrictStr] = Field(default=None, description="Url to claim insurance for this policy.")
    certificate_url: Optional[StrictStr] = Field(default=None, description="Url to request for Travel Insurance certificate from provider.")
    emergency_phone_number: Optional[StrictStr] = Field(default=None, description="Phone number for emergencies/claims.")
    __properties: ClassVar[List[str]] = ["policy_number", "user_creator", "user_insured", "status", "reason_cancel", "country", "claim_url", "certificate_url", "emergency_phone_number"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TravelInsurancePolicyListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "policy_number",
                "status",
                "reason_cancel",
                "country",
                "claim_url",
                "certificate_url",
                "emergency_phone_number",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user_creator
        if self.user_creator:
            _dict['user_creator'] = self.user_creator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_insured
        if self.user_insured:
            _dict['user_insured'] = self.user_insured.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TravelInsurancePolicyListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "policy_number": obj.get("policy_number"),
            "user_creator": LabelUser.from_dict(obj.get("user_creator")) if obj.get("user_creator") is not None else None,
            "user_insured": LabelUser.from_dict(obj.get("user_insured")) if obj.get("user_insured") is not None else None,
            "status": obj.get("status"),
            "reason_cancel": obj.get("reason_cancel"),
            "country": obj.get("country"),
            "claim_url": obj.get("claim_url"),
            "certificate_url": obj.get("certificate_url"),
            "emergency_phone_number": obj.get("emergency_phone_number")
        })
        return _obj


