# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserAuditEntryObject(BaseModel):
    """
    UserAuditEntryObject
    """ # noqa: E501
    admin_comment_risk_user: Optional[Dict[str, Any]] = Field(default=None, alias="AdminCommentRiskUser")
    admin_comment_user_user_transaction_monitoring_metadata: Optional[Dict[str, Any]] = Field(default=None, alias="AdminCommentUserUserTransactionMonitoringMetadata")
    fiu_report: Optional[Dict[str, Any]] = Field(default=None, alias="FiuReport")
    dow_jones_entry: Optional[Dict[str, Any]] = Field(default=None, alias="DowJonesEntry")
    user_recovery_expiry_identification_document: Optional[Dict[str, Any]] = Field(default=None, alias="UserRecoveryExpiryIdentificationDocument")
    user_recovery_expiry_tax_identification_number: Optional[Dict[str, Any]] = Field(default=None, alias="UserRecoveryExpiryTaxIdentificationNumber")
    user_recovery_expiry_company_risk_information: Optional[Dict[str, Any]] = Field(default=None, alias="UserRecoveryExpiryCompanyRiskInformation")
    user_recovery_expiry_person_risk_information: Optional[Dict[str, Any]] = Field(default=None, alias="UserRecoveryExpiryPersonRiskInformation")
    user_recovery_expiry_review_check: Optional[Dict[str, Any]] = Field(default=None, alias="UserRecoveryExpiryReviewCheck")
    user_review: Optional[Dict[str, Any]] = Field(default=None, alias="UserReview")
    assessment_fiu: Optional[Dict[str, Any]] = Field(default=None, alias="AssessmentFiu")
    assessment_terror: Optional[Dict[str, Any]] = Field(default=None, alias="AssessmentTerror")
    assessment_marketplace: Optional[Dict[str, Any]] = Field(default=None, alias="AssessmentMarketplace")
    assessment_swift: Optional[Dict[str, Any]] = Field(default=None, alias="AssessmentSwift")
    assessment_fraud: Optional[Dict[str, Any]] = Field(default=None, alias="AssessmentFraud")
    risk: Optional[Dict[str, Any]] = Field(default=None, alias="Risk")
    __properties: ClassVar[List[str]] = ["AdminCommentRiskUser", "AdminCommentUserUserTransactionMonitoringMetadata", "FiuReport", "DowJonesEntry", "UserRecoveryExpiryIdentificationDocument", "UserRecoveryExpiryTaxIdentificationNumber", "UserRecoveryExpiryCompanyRiskInformation", "UserRecoveryExpiryPersonRiskInformation", "UserRecoveryExpiryReviewCheck", "UserReview", "AssessmentFiu", "AssessmentTerror", "AssessmentMarketplace", "AssessmentSwift", "AssessmentFraud", "Risk"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserAuditEntryObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of admin_comment_risk_user
        if self.admin_comment_risk_user:
            _dict['AdminCommentRiskUser'] = self.admin_comment_risk_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of admin_comment_user_user_transaction_monitoring_metadata
        if self.admin_comment_user_user_transaction_monitoring_metadata:
            _dict['AdminCommentUserUserTransactionMonitoringMetadata'] = self.admin_comment_user_user_transaction_monitoring_metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fiu_report
        if self.fiu_report:
            _dict['FiuReport'] = self.fiu_report.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dow_jones_entry
        if self.dow_jones_entry:
            _dict['DowJonesEntry'] = self.dow_jones_entry.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_recovery_expiry_identification_document
        if self.user_recovery_expiry_identification_document:
            _dict['UserRecoveryExpiryIdentificationDocument'] = self.user_recovery_expiry_identification_document.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_recovery_expiry_tax_identification_number
        if self.user_recovery_expiry_tax_identification_number:
            _dict['UserRecoveryExpiryTaxIdentificationNumber'] = self.user_recovery_expiry_tax_identification_number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_recovery_expiry_company_risk_information
        if self.user_recovery_expiry_company_risk_information:
            _dict['UserRecoveryExpiryCompanyRiskInformation'] = self.user_recovery_expiry_company_risk_information.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_recovery_expiry_person_risk_information
        if self.user_recovery_expiry_person_risk_information:
            _dict['UserRecoveryExpiryPersonRiskInformation'] = self.user_recovery_expiry_person_risk_information.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_recovery_expiry_review_check
        if self.user_recovery_expiry_review_check:
            _dict['UserRecoveryExpiryReviewCheck'] = self.user_recovery_expiry_review_check.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_review
        if self.user_review:
            _dict['UserReview'] = self.user_review.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assessment_fiu
        if self.assessment_fiu:
            _dict['AssessmentFiu'] = self.assessment_fiu.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assessment_terror
        if self.assessment_terror:
            _dict['AssessmentTerror'] = self.assessment_terror.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assessment_marketplace
        if self.assessment_marketplace:
            _dict['AssessmentMarketplace'] = self.assessment_marketplace.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assessment_swift
        if self.assessment_swift:
            _dict['AssessmentSwift'] = self.assessment_swift.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assessment_fraud
        if self.assessment_fraud:
            _dict['AssessmentFraud'] = self.assessment_fraud.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risk
        if self.risk:
            _dict['Risk'] = self.risk.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserAuditEntryObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AdminCommentRiskUser": AdminCommentRiskUser.from_dict(obj.get("AdminCommentRiskUser")) if obj.get("AdminCommentRiskUser") is not None else None,
            "AdminCommentUserUserTransactionMonitoringMetadata": AdminCommentRiskUserTransactionMonitoringMetadata.from_dict(obj.get("AdminCommentUserUserTransactionMonitoringMetadata")) if obj.get("AdminCommentUserUserTransactionMonitoringMetadata") is not None else None,
            "FiuReport": FiuReport.from_dict(obj.get("FiuReport")) if obj.get("FiuReport") is not None else None,
            "DowJonesEntry": DowJonesCheck.from_dict(obj.get("DowJonesEntry")) if obj.get("DowJonesEntry") is not None else None,
            "UserRecoveryExpiryIdentificationDocument": UserRecoveryExpiry.from_dict(obj.get("UserRecoveryExpiryIdentificationDocument")) if obj.get("UserRecoveryExpiryIdentificationDocument") is not None else None,
            "UserRecoveryExpiryTaxIdentificationNumber": UserRecoveryExpiry.from_dict(obj.get("UserRecoveryExpiryTaxIdentificationNumber")) if obj.get("UserRecoveryExpiryTaxIdentificationNumber") is not None else None,
            "UserRecoveryExpiryCompanyRiskInformation": UserRecoveryExpiry.from_dict(obj.get("UserRecoveryExpiryCompanyRiskInformation")) if obj.get("UserRecoveryExpiryCompanyRiskInformation") is not None else None,
            "UserRecoveryExpiryPersonRiskInformation": UserRecoveryExpiry.from_dict(obj.get("UserRecoveryExpiryPersonRiskInformation")) if obj.get("UserRecoveryExpiryPersonRiskInformation") is not None else None,
            "UserRecoveryExpiryReviewCheck": UserRecoveryExpiryReviewCheck.from_dict(obj.get("UserRecoveryExpiryReviewCheck")) if obj.get("UserRecoveryExpiryReviewCheck") is not None else None,
            "UserReview": UserReview.from_dict(obj.get("UserReview")) if obj.get("UserReview") is not None else None,
            "AssessmentFiu": Assessment.from_dict(obj.get("AssessmentFiu")) if obj.get("AssessmentFiu") is not None else None,
            "AssessmentTerror": Assessment.from_dict(obj.get("AssessmentTerror")) if obj.get("AssessmentTerror") is not None else None,
            "AssessmentMarketplace": Assessment.from_dict(obj.get("AssessmentMarketplace")) if obj.get("AssessmentMarketplace") is not None else None,
            "AssessmentSwift": Assessment.from_dict(obj.get("AssessmentSwift")) if obj.get("AssessmentSwift") is not None else None,
            "AssessmentFraud": Assessment.from_dict(obj.get("AssessmentFraud")) if obj.get("AssessmentFraud") is not None else None,
            "Risk": TransactionMonitoringMetadata.from_dict(obj.get("Risk")) if obj.get("Risk") is not None else None
        })
        return _obj


