# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.notification_filter import NotificationFilter
from openapi_server.models.pointer import Pointer
from openapi_server.models.relation_user import RelationUser
from openapi_server.models.tax_resident import TaxResident
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserPerson(BaseModel):
    """
    UserPerson
    """ # noqa: E501
    subscription_type: Optional[StrictStr] = Field(default=None, description="The subscription type the user should start on.")
    first_name: Optional[StrictStr] = Field(default=None, description="The person's first name.")
    middle_name: Optional[StrictStr] = Field(default=None, description="The person's middle name.")
    last_name: Optional[StrictStr] = Field(default=None, description="The person's last name.")
    public_nick_name: Optional[StrictStr] = Field(default=None, description="The public nick name for the person.")
    address_main: Optional[Dict[str, Any]] = None
    address_postal: Optional[Dict[str, Any]] = None
    avatar_uuid: Optional[StrictStr] = Field(default=None, description="The public UUID of the user's avatar.")
    tax_resident: Optional[List[TaxResident]] = Field(default=None, description="The user's tax residence numbers for different countries.")
    document_type: Optional[StrictStr] = Field(default=None, description="The type of identification document the person registered with.")
    document_number: Optional[StrictStr] = Field(default=None, description="The identification document number the person registered with.")
    document_country_of_issuance: Optional[StrictStr] = Field(default=None, description="The country which issued the identification document the person registered with.")
    document_front_attachment_id: Optional[StrictInt] = Field(default=None, description="The reference to the uploaded picture/scan of the front side of the identification document.")
    document_back_attachment_id: Optional[StrictInt] = Field(default=None, description="The reference to the uploaded picture/scan of the back side of the identification document.")
    date_of_birth: Optional[StrictStr] = Field(default=None, description="The person's date of birth. Accepts ISO8601 date formats.")
    nationality: Optional[StrictStr] = Field(default=None, description="The person's nationality. Formatted as a SO 3166-1 alpha-2 country code.")
    all_nationality: Optional[List[StrictStr]] = Field(default=None, description="All of the person's nationalities.")
    language: Optional[StrictStr] = Field(default=None, description="The person's preferred language. Formatted as a ISO 639-1 language code plus a ISO 3166-1 alpha-2 country code, seperated by an underscore.")
    region: Optional[StrictStr] = Field(default=None, description="The person's preferred region. Formatted as a ISO 639-1 language code plus a ISO 3166-1 alpha-2 country code, seperated by an underscore.")
    gender: Optional[StrictStr] = Field(default=None, description="The person's gender. Can be MALE, FEMALE or UNKNOWN.")
    status: Optional[StrictStr] = Field(default=None, description="The user status. The user status. Can be: ACTIVE, BLOCKED, SIGNUP, RECOVERY, DENIED or ABORTED.")
    sub_status: Optional[StrictStr] = Field(default=None, description="The user sub-status. Can be: NONE, FACE_RESET, APPROVAL, APPROVAL_DIRECTOR, APPROVAL_PARENT, APPROVAL_SUPPORT, COUNTER_IBAN, IDEAL or SUBMIT.")
    legal_guardian_alias: Optional[Dict[str, Any]] = None
    session_timeout: Optional[StrictInt] = Field(default=None, description="The setting for the session timeout of the user in seconds.")
    daily_limit_without_confirmation_login: Optional[Dict[str, Any]] = None
    display_name: Optional[StrictStr] = Field(default=None, description="The display name for the person.")
    signup_track_type: Optional[StrictStr] = Field(default=None, description="The type of signup track the user is following.")
    id: Optional[StrictInt] = Field(default=None, description="The id of the modified person object.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the person object's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the person object's last update.")
    public_uuid: Optional[StrictStr] = Field(default=None, description="The person's public UUID.")
    legal_name: Optional[StrictStr] = Field(default=None, description="The person's legal name.")
    alias: Optional[List[Pointer]] = Field(default=None, description="The aliases of the user.")
    address_shipping: Optional[Dict[str, Any]] = None
    place_of_birth: Optional[StrictStr] = Field(default=None, description="The person's place of birth.")
    country_of_birth: Optional[StrictStr] = Field(default=None, description="The person's country of birth. Formatted as a SO 3166-1 alpha-2 country code.")
    avatar: Optional[Dict[str, Any]] = None
    version_terms_of_service: Optional[StrictStr] = Field(default=None, description="The version of the terms of service accepted by the user.")
    notification_filters: Optional[List[NotificationFilter]] = Field(default=None, description="The types of notifications that will result in a push notification or URL callback for this UserPerson.")
    relations: Optional[List[RelationUser]] = Field(default=None, description="The relations for this user.")
    __properties: ClassVar[List[str]] = ["subscription_type", "first_name", "middle_name", "last_name", "public_nick_name", "address_main", "address_postal", "avatar_uuid", "tax_resident", "document_type", "document_number", "document_country_of_issuance", "document_front_attachment_id", "document_back_attachment_id", "date_of_birth", "nationality", "all_nationality", "language", "region", "gender", "status", "sub_status", "legal_guardian_alias", "session_timeout", "daily_limit_without_confirmation_login", "display_name", "signup_track_type", "id", "created", "updated", "public_uuid", "legal_name", "alias", "address_shipping", "place_of_birth", "country_of_birth", "avatar", "version_terms_of_service", "notification_filters", "relations"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserPerson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "public_uuid",
                "legal_name",
                "alias",
                "place_of_birth",
                "country_of_birth",
                "version_terms_of_service",
                "notification_filters",
                "relations",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address_main
        if self.address_main:
            _dict['address_main'] = self.address_main.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address_postal
        if self.address_postal:
            _dict['address_postal'] = self.address_postal.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tax_resident (list)
        _items = []
        if self.tax_resident:
            for _item in self.tax_resident:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tax_resident'] = _items
        # override the default output from pydantic by calling `to_dict()` of legal_guardian_alias
        if self.legal_guardian_alias:
            _dict['legal_guardian_alias'] = self.legal_guardian_alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of daily_limit_without_confirmation_login
        if self.daily_limit_without_confirmation_login:
            _dict['daily_limit_without_confirmation_login'] = self.daily_limit_without_confirmation_login.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in alias (list)
        _items = []
        if self.alias:
            for _item in self.alias:
                if _item:
                    _items.append(_item.to_dict())
            _dict['alias'] = _items
        # override the default output from pydantic by calling `to_dict()` of address_shipping
        if self.address_shipping:
            _dict['address_shipping'] = self.address_shipping.to_dict()
        # override the default output from pydantic by calling `to_dict()` of avatar
        if self.avatar:
            _dict['avatar'] = self.avatar.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notification_filters (list)
        _items = []
        if self.notification_filters:
            for _item in self.notification_filters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['notification_filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in relations (list)
        _items = []
        if self.relations:
            for _item in self.relations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['relations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserPerson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subscription_type": obj.get("subscription_type"),
            "first_name": obj.get("first_name"),
            "middle_name": obj.get("middle_name"),
            "last_name": obj.get("last_name"),
            "public_nick_name": obj.get("public_nick_name"),
            "address_main": Address.from_dict(obj.get("address_main")) if obj.get("address_main") is not None else None,
            "address_postal": Address.from_dict(obj.get("address_postal")) if obj.get("address_postal") is not None else None,
            "avatar_uuid": obj.get("avatar_uuid"),
            "tax_resident": [TaxResident.from_dict(_item) for _item in obj.get("tax_resident")] if obj.get("tax_resident") is not None else None,
            "document_type": obj.get("document_type"),
            "document_number": obj.get("document_number"),
            "document_country_of_issuance": obj.get("document_country_of_issuance"),
            "document_front_attachment_id": obj.get("document_front_attachment_id"),
            "document_back_attachment_id": obj.get("document_back_attachment_id"),
            "date_of_birth": obj.get("date_of_birth"),
            "nationality": obj.get("nationality"),
            "all_nationality": obj.get("all_nationality"),
            "language": obj.get("language"),
            "region": obj.get("region"),
            "gender": obj.get("gender"),
            "status": obj.get("status"),
            "sub_status": obj.get("sub_status"),
            "legal_guardian_alias": Pointer.from_dict(obj.get("legal_guardian_alias")) if obj.get("legal_guardian_alias") is not None else None,
            "session_timeout": obj.get("session_timeout"),
            "daily_limit_without_confirmation_login": Amount.from_dict(obj.get("daily_limit_without_confirmation_login")) if obj.get("daily_limit_without_confirmation_login") is not None else None,
            "display_name": obj.get("display_name"),
            "signup_track_type": obj.get("signup_track_type"),
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "public_uuid": obj.get("public_uuid"),
            "legal_name": obj.get("legal_name"),
            "alias": [Pointer.from_dict(_item) for _item in obj.get("alias")] if obj.get("alias") is not None else None,
            "address_shipping": Address.from_dict(obj.get("address_shipping")) if obj.get("address_shipping") is not None else None,
            "place_of_birth": obj.get("place_of_birth"),
            "country_of_birth": obj.get("country_of_birth"),
            "avatar": Avatar.from_dict(obj.get("avatar")) if obj.get("avatar") is not None else None,
            "version_terms_of_service": obj.get("version_terms_of_service"),
            "notification_filters": [NotificationFilter.from_dict(_item) for _item in obj.get("notification_filters")] if obj.get("notification_filters") is not None else None,
            "relations": [RelationUser.from_dict(_item) for _item in obj.get("relations")] if obj.get("relations") is not None else None
        })
        return _obj


