# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserReviewValueIdentificationDocument(BaseModel):
    """
    UserReviewValueIdentificationDocument
    """ # noqa: E501
    document_type: Optional[StrictStr] = Field(default=None, description="The document type that is associated to this value.")
    document_description: Optional[StrictStr] = Field(default=None, description="A description of the requested document type. Only allowed for type 'UNKNOWN'.")
    identification_document_id: Optional[StrictInt] = Field(default=None, description="The id of the associated identification document.")
    company_person_id: Optional[StrictInt] = Field(default=None, description="The id of the company person this document is for.")
    status: Optional[StrictStr] = Field(default=None, description="Status of the review value.")
    identification_document: Optional[Dict[str, Any]] = None
    document_type_title: Optional[StrictStr] = Field(default=None, description="The human readable document type title that is associated to this value.")
    description: Optional[StrictStr] = Field(default=None, description="The description for the user of the instructions to follow")
    deny_reason: Optional[StrictStr] = Field(default=None, description="The reason why a document is rejected (null if unavailable).")
    together_url: Optional[StrictStr] = Field(default=None, description="The URL for the Together topic (null if unavailable).")
    template_url: Optional[StrictStr] = Field(default=None, description="The URL for the document to fill")
    __properties: ClassVar[List[str]] = ["document_type", "document_description", "identification_document_id", "company_person_id", "status", "identification_document", "document_type_title", "description", "deny_reason", "together_url", "template_url"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserReviewValueIdentificationDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "document_type_title",
                "description",
                "deny_reason",
                "together_url",
                "template_url",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of identification_document
        if self.identification_document:
            _dict['identification_document'] = self.identification_document.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserReviewValueIdentificationDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "document_type": obj.get("document_type"),
            "document_description": obj.get("document_description"),
            "identification_document_id": obj.get("identification_document_id"),
            "company_person_id": obj.get("company_person_id"),
            "status": obj.get("status"),
            "identification_document": DocumentIdentification.from_dict(obj.get("identification_document")) if obj.get("identification_document") is not None else None,
            "document_type_title": obj.get("document_type_title"),
            "description": obj.get("description"),
            "deny_reason": obj.get("deny_reason"),
            "together_url": obj.get("together_url"),
            "template_url": obj.get("template_url")
        })
        return _obj


