# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserAdminSettingListing(BaseModel):
    """
    UserAdminSettingListing
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the settings.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the setting object's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the setting object's last update.")
    display_ticket_counts_in_homepage: Optional[StrictStr] = Field(default=None, description="If the ticket count should be displayed in the homepage. Can be YES or NO.")
    display_monitoring_hits_in_sidebar: Optional[StrictStr] = Field(default=None, description="If the monitoring hits should be displayed in the sidebar. Can be YES, NO or ONLY_MORE_THAN_ZERO.")
    display_open_chats_count_in_sidebar: Optional[StrictStr] = Field(default=None, description="If the number of open chats should be displayed in the sidebar. Can be YES or ONLY_MORE_THAN_ZERO.")
    play_sound_for_new_orphan: Optional[StrictStr] = Field(default=None, description="If a sound should be played when there is a new orphan chat. Can be YES or NO.")
    play_sound_for_new_user_approval: Optional[StrictStr] = Field(default=None, description="If a sound should be played when there is a new pending user approval. Can be YES or NO.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "display_ticket_counts_in_homepage", "display_monitoring_hits_in_sidebar", "display_open_chats_count_in_sidebar", "play_sound_for_new_orphan", "play_sound_for_new_user_approval"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserAdminSettingListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "display_ticket_counts_in_homepage",
                "display_monitoring_hits_in_sidebar",
                "display_open_chats_count_in_sidebar",
                "play_sound_for_new_orphan",
                "play_sound_for_new_user_approval",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserAdminSettingListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "display_ticket_counts_in_homepage": obj.get("display_ticket_counts_in_homepage"),
            "display_monitoring_hits_in_sidebar": obj.get("display_monitoring_hits_in_sidebar"),
            "display_open_chats_count_in_sidebar": obj.get("display_open_chats_count_in_sidebar"),
            "play_sound_for_new_orphan": obj.get("play_sound_for_new_orphan"),
            "play_sound_for_new_user_approval": obj.get("play_sound_for_new_user_approval")
        })
        return _obj


