# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.identification_verification_failure_reason import IdentificationVerificationFailureReason
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserIdentificationVerificationRead(BaseModel):
    """
    UserIdentificationVerificationRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the modified user object.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the identification object's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the identification object's last update.")
    applicant_id: Optional[StrictStr] = Field(default=None, description="The applicant ID, given by Onfido.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the identification object.")
    token: Optional[StrictStr] = Field(default=None, description="The token used by the apps to upload documents.")
    result_url: Optional[StrictStr] = Field(default=None, description="The result url of Onfido check object.")
    failed_reasons: Optional[List[IdentificationVerificationFailureReason]] = Field(default=None, description="The reasons given by verification for failing.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "applicant_id", "status", "token", "result_url", "failed_reasons"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserIdentificationVerificationRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "applicant_id",
                "status",
                "token",
                "result_url",
                "failed_reasons",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in failed_reasons (list)
        _items = []
        if self.failed_reasons:
            for _item in self.failed_reasons:
                if _item:
                    _items.append(_item.to_dict())
            _dict['failed_reasons'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserIdentificationVerificationRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "applicant_id": obj.get("applicant_id"),
            "status": obj.get("status"),
            "token": obj.get("token"),
            "result_url": obj.get("result_url"),
            "failed_reasons": [IdentificationVerificationFailureReason.from_dict(_item) for _item in obj.get("failed_reasons")] if obj.get("failed_reasons") is not None else None
        })
        return _obj


