# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.identification_verification_attachment import IdentificationVerificationAttachment
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserIdentificationVerificationReportRead(BaseModel):
    """
    UserIdentificationVerificationReportRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the identification.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the identification object's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the identification object's last update.")
    report_id: Optional[StrictStr] = Field(default=None, description="The report ID, given by Onfido.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the identification object.")
    type: Optional[StrictStr] = Field(default=None, description="The type of report. Can be document or facial_similarity")
    sub_type: Optional[StrictStr] = Field(default=None, description="The sub-type of the report. Can be video or photo.")
    result: Optional[StrictStr] = Field(default=None, description="The result of the report.")
    sub_result: Optional[StrictStr] = Field(default=None, description="The sub-result of the report.")
    result_breakdown: Optional[StrictStr] = Field(default=None, description="The token used by the apps to upload documents.")
    result_score: Optional[StrictStr] = Field(default=None, description="The score of the result of the report between 0 and 1.")
    attachment: Optional[List[IdentificationVerificationAttachment]] = Field(default=None, description="The attachments attached.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "report_id", "status", "type", "sub_type", "result", "sub_result", "result_breakdown", "result_score", "attachment"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserIdentificationVerificationReportRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "report_id",
                "status",
                "type",
                "sub_type",
                "result",
                "sub_result",
                "result_breakdown",
                "result_score",
                "attachment",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachment (list)
        _items = []
        if self.attachment:
            for _item in self.attachment:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attachment'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserIdentificationVerificationReportRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "report_id": obj.get("report_id"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "sub_type": obj.get("sub_type"),
            "result": obj.get("result"),
            "sub_result": obj.get("sub_result"),
            "result_breakdown": obj.get("result_breakdown"),
            "result_score": obj.get("result_score"),
            "attachment": [IdentificationVerificationAttachment.from_dict(_item) for _item in obj.get("attachment")] if obj.get("attachment") is not None else None
        })
        return _obj


