# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserSettingKrakenListing(BaseModel):
    """
    UserSettingKrakenListing
    """ # noqa: E501
    preference_sharing: Optional[StrictStr] = Field(default=None, description="Preference for sharing activity of Kraken with contacts.")
    preference_delayed_withdrawal: Optional[StrictStr] = Field(default=None, description="Preference for delayed withdrawal.")
    preference_delayed_withdrawal_status: Optional[StrictStr] = Field(default=None, description="Status for preference for delayed withdrawal.")
    preference_delayed_withdrawal_time_process: Optional[StrictStr] = Field(default=None, description="When the user setting will be updated.")
    all_asset_favorite: Optional[List[StrictStr]] = Field(default=None, description="List of favorite assets.")
    __properties: ClassVar[List[str]] = ["preference_sharing", "preference_delayed_withdrawal", "preference_delayed_withdrawal_status", "preference_delayed_withdrawal_time_process", "all_asset_favorite"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserSettingKrakenListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "preference_sharing",
                "preference_delayed_withdrawal",
                "preference_delayed_withdrawal_status",
                "preference_delayed_withdrawal_time_process",
                "all_asset_favorite",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserSettingKrakenListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "preference_sharing": obj.get("preference_sharing"),
            "preference_delayed_withdrawal": obj.get("preference_delayed_withdrawal"),
            "preference_delayed_withdrawal_status": obj.get("preference_delayed_withdrawal_status"),
            "preference_delayed_withdrawal_time_process": obj.get("preference_delayed_withdrawal_time_process"),
            "all_asset_favorite": obj.get("all_asset_favorite")
        })
        return _obj


