# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserApprovalRead(BaseModel):
    """
    UserApprovalRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the approval.")
    created: Optional[StrictStr] = Field(default=None, description="The timestamp of the approval's creation.")
    updated: Optional[StrictStr] = Field(default=None, description="The timestamp of the approval's last update.")
    alias: Optional[Dict[str, Any]] = None
    user_country: Optional[StrictStr] = Field(default=None, description="The country the user to be approved is currently located.")
    alias_assigned: Optional[Dict[str, Any]] = None
    status: Optional[StrictStr] = Field(default=None, description="The status of the user approval.")
    reactivation: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "alias", "user_country", "alias_assigned", "status", "reactivation"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserApprovalRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "user_country",
                "status",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of alias_assigned
        if self.alias_assigned:
            _dict['alias_assigned'] = self.alias_assigned.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reactivation
        if self.reactivation:
            _dict['reactivation'] = self.reactivation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserApprovalRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "alias": LabelUser.from_dict(obj.get("alias")) if obj.get("alias") is not None else None,
            "user_country": obj.get("user_country"),
            "alias_assigned": LabelUser.from_dict(obj.get("alias_assigned")) if obj.get("alias_assigned") is not None else None,
            "status": obj.get("status"),
            "reactivation": UserReactivation.from_dict(obj.get("reactivation")) if obj.get("reactivation") is not None else None
        })
        return _obj


