# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserRecoveryExpiry(BaseModel):
    """
    UserRecoveryExpiry
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="The type of the recovery requirement. Valid values are IDENTIFICATION_DOCUMENT, TAX_IDENTIFICATION_NUMBER, COMPANY_RISK_INFORMATION & PERSON_RISK_INFORMATION. **Deprecated:** Use the object type instead.")
    expiry_time: Optional[StrictStr] = Field(default=None, description="When the user will be moved to status RECOVERY/NONE if he hasn't yet met the recovery requirement.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the recovery expiry. Valid values are WAITING_FOR_USER_RESPONSE, USER_RESPONDED & RECOVERY_EXPIRED.")
    tin_status_confirmation: Optional[StrictStr] = Field(default=None, description="The status of the TIN confirmation. Valid values are UNCONFIRMED, REQUESTED_CONFIRMATION & CONFIRMED.")
    tin_time_confirmation: Optional[StrictStr] = Field(default=None, description="The timestamp at which the TIN confirmation will be requested.")
    tin_time_next_warning: Optional[StrictStr] = Field(default=None, description="The timestamp at which the next warning should be issued, at the very least.")
    tin_status_warning: Optional[StrictStr] = Field(default=None, description="The status of the TIN confirmation warning.")
    __properties: ClassVar[List[str]] = ["type", "expiry_time", "status", "tin_status_confirmation", "tin_time_confirmation", "tin_time_next_warning", "tin_status_warning"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserRecoveryExpiry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "status",
                "tin_status_confirmation",
                "tin_time_confirmation",
                "tin_time_next_warning",
                "tin_status_warning",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserRecoveryExpiry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "expiry_time": obj.get("expiry_time"),
            "status": obj.get("status"),
            "tin_status_confirmation": obj.get("tin_status_confirmation"),
            "tin_time_confirmation": obj.get("tin_time_confirmation"),
            "tin_time_next_warning": obj.get("tin_time_next_warning"),
            "tin_status_warning": obj.get("tin_status_warning")
        })
        return _obj


