# coding: utf-8

"""
    bunq API

    WIL BE POPULATED WITH THE TEXT IN DESCRIPTION.md

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.watchlist_result import WatchlistResult
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WatchlistCheckRead(BaseModel):
    """
    WatchlistCheckRead
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the watchlist check.")
    created: Optional[StrictStr] = Field(default=None, description="The time at which the watchlist check was created.")
    updated: Optional[StrictStr] = Field(default=None, description="The time at which the watchlist check was last updated.")
    user_id: Optional[StrictInt] = Field(default=None, description="The user this check is for.")
    decision: Optional[StrictStr] = Field(default=None, description="The decision as made by the 3rd party watchlist provider.")
    all_result: Optional[List[WatchlistResult]] = Field(default=None, description="The results from this check.")
    external_url: Optional[StrictStr] = Field(default=None, description="The URL that can be used to view the result of this WatchlistCheck at the provider.")
    __properties: ClassVar[List[str]] = ["id", "created", "updated", "user_id", "decision", "all_result", "external_url"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WatchlistCheckRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "id",
                "created",
                "updated",
                "user_id",
                "decision",
                "all_result",
                "external_url",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in all_result (list)
        _items = []
        if self.all_result:
            for _item in self.all_result:
                if _item:
                    _items.append(_item.to_dict())
            _dict['all_result'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WatchlistCheckRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "user_id": obj.get("user_id"),
            "decision": obj.get("decision"),
            "all_result": [WatchlistResult.from_dict(_item) for _item in obj.get("all_result")] if obj.get("all_result") is not None else None,
            "external_url": obj.get("external_url")
        })
        return _obj


